=== astroChasqui/websoccer_es/modules/messages.dtd
<!ELEMENT messages (message+)>

<!ELEMENT message (#PCDATA|strong|b|i|a|em|p|ul|br)*>
<!ATTLIST message id CDATA #REQUIRED>

<!ELEMENT strong (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT em (#PCDATA)>
<!ELEMENT p (#PCDATA|strong|b|i|a|em|p|ul)*>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #IMPLIED>
<!ATTLIST a target CDATA #IMPLIED>
<!ATTLIST a class CDATA #IMPLIED>

<!ELEMENT ul (li+)>
<!ELEMENT li (#PCDATA)>

<!ELEMENT br (#PCDATA)>

=== astroChasqui/websoccer_es/modules/nationalteams/messages_en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "../messages.dtd">
<messages>
    <message id="nationalteam_navlabel">National Team</message>
    <message id="nationalmatches_navlabel">Matches</message>
    <message id="nominate-national-players_navlabel">Nominate Players</message>
    <message id="nationalteams_user_requires_team">You need to be the manager of a national team in order to use this feature.</message>
    <message id="nationalteams_no_players">You have not nominated any players, yet.</message>
    <message id="nationalteams_addplayer">Nominate</message>
    <message id="nationalteams_addplayer_err_alreadyinteam">The player already belongs to your team.</message>
    <message id="nationalteams_addplayer_err_toomanyplayer">You may nominate only up to %d players.</message>
    <message id="nationalteams_addplayer_success">The player has been successfully added to your team.</message>
    <message id="nationalteams_remove_from_team">Remove</message>
    <message id="nationalteams_removeplayer_success">The player has been successfully removed from your team.</message>
    <message id="nationalteams_team_label">National Team</message>
    <message id="nationalmatches_title">National Team Matches</message>
    <message id="nationalmatches_next_title">Next Matches</message>
	<message id="nationalmatches_results_title">Results</message>
	
	<message id="nationalmatches_nextmatch_title">Next national team match</message>
</messages>

=== astroChasqui/websoccer_es/modules/core/messages_en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../messages.dtd">
<messages>
	<message id="offline_title">We are temporarily offline</message>
	<message id="error_action_required_team">You need to be manager of a team in order to execute this action.</message>
	
	<message id="requireslogin_box_title">Access denied</message>
	<message id="requireslogin_box_message">You need to be logged on in order to see the site content.</message>
	
	<message id="date_yesterday">Yesterday</message>
	<message id="date_today">Today</message>
	<message id="date_tomorrow">Tomorrow</message>
	
	<message id="privacypolicy_navlabel">Privacy policy</message>
</messages>

=== astroChasqui/websoccer_es/modules/userregistration/adminmessages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../messages.dtd">
<messages>
    <message id="settings_label_allow_userregistration">Benutzerregistrierung für jeden Gast aktivieren.</message> 
    <message id="settings_label_illegal_usernames">Unerlaubte Benutzernamen</message> 
    <message id="settings_label_illegal_usernames_help">Mit Komma getrennt</message> 
    <message id="settings_label_max_number_of_users">Höchstanzahl zugelassender Benutzer</message> 
    <message id="settings_label_max_number_of_users_help">0 für uneingeschränkt</message> 
    
    <message id="settings_label_register_use_captcha">reCAPTCHA Sicherheitscode benutzen, um Spam-Registrierungen zu verhindern. Dies erfordert eine Registrierung auf <a href="https://www.google.com/recaptcha/admin/create" target="_blank">www.google.com/recaptcha</a>.</message> 
    
    <message id="settings_label_register_captcha_publickey">Public Key</message>
    <message id="settings_label_register_captcha_publickey_help">Entnehmen Sie diese Angabe aus der reCAPTCHA-Registrierungsbestätigung.</message>
    <message id="settings_label_register_captcha_privatekey">Private Key</message>
    <message id="settings_label_register_captcha_privatekey_help">Entnehmen Sie diese Angabe aus der reCAPTCHA-Registrierungsbestätigung.</message>

    <message id="settings_label_registration_url">URL zu Registrierung</message>
	<message id="settings_label_registration_url_help">Falls Benutzer ihr Benutzerkonto auf einer anderen Webseite registrieren sollen, können Sie hier den URL zur Registrierungsmaske angeben.</message>
</messages>

=== astroChasqui/websoccer_es/modules/stadiumenvironment/entitymessages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "../messages.dtd">
<messages>
    <message id="entity_stadiumbuilding">Gebäude</message>
	<message id="entity_stadiumbuilding_name">Name</message>
	<message id="entity_stadiumbuilding_name_help">Kann auch ein Messages-Key sein.</message>
	<message id="entity_stadiumbuilding_description">Beschreibung</message>
	<message id="entity_stadiumbuilding_description_help">Kann auch ein Messages-Key sein.</message>
	<message id="entity_stadiumbuilding_picture">Bild</message>
	
	<message id="entity_stadiumbuilding_required_building_id">Erforderliches Gebäude</message>
	<message id="entity_stadiumbuilding_required_building_id_help">Ein ausgewähltes Gebäude muss dann vorher gebaut werden. Beachten Sie, dass das vorher gebaute Gebäude auch nach Bau des neuen Gebäudes erhalten bleibt. Die unten eingegebenen Auswirkungen werden dann aufaddiert.</message>
	
	<message id="entity_stadiumbuilding_costs">Baukosten</message>
	<message id="entity_stadiumbuilding_premiumfee">Premiumkosten</message>
	<message id="entity_stadiumbuilding_premiumfee_help">Das Premiumkonto des Benutzers wird dann zusätzlich zum Vereinskonto belastet.</message>
	<message id="entity_stadiumbuilding_construction_time_days">Bauzeit (Tage)</message>
	<message id="entity_stadiumbuilding_effect_training">Auswirkung: Training</message>
	<message id="entity_stadiumbuilding_effect_training_help">Wieviele Stärkepunkte an Frische und Zufriedenheit pro Trainingseinheit zusätzlich gewonnen werden kann.</message>
	<message id="entity_stadiumbuilding_effect_youthscouting">Auswirkung: Jugendscouting</message>
	<message id="entity_stadiumbuilding_effect_youthscouting_help">Stärkebonus bei gefundenen Jugendspielern.</message>
	<message id="entity_stadiumbuilding_effect_tickets">Auswirkung: Zuschauer</message>
	<message id="entity_stadiumbuilding_effect_tickets_help">Um wieviel Prozentpunkte mehr Tickets verkauft werden bei Heimspielen. Bonus verfällt wenn ohne Gebäudebonus gar keine Tickets verkauft würden.</message>
	<message id="entity_stadiumbuilding_effect_fanpopularity">Auswirkung: Fanbeliebtheit (einmalig)</message>
	<message id="entity_stadiumbuilding_effect_fanpopularity_help">Um wieviel Prozentpunkte die Fanbeliebtheit des Benutzers einmalig geändert wird. <strong>Achtung:</strong> Die Auswirkung wird sofort bei Bauerteilung gutgeschrieben. Die Bauzeit wird hier nicht berücksichtigt.</message>
    <message id="entity_stadiumbuilding_effect_injury">Auswirkung: Verletzungen</message>
    <message id="entity_stadiumbuilding_effect_injury_help">Um wieviele Spiele die Verletzung von Spielern nach jedem Spiel zusätzlich zur normalen Genesung reduziert werden soll. Beispiel: Wert 1 halbiert die Genesungszeit.</message>
    <message id="entity_stadiumbuilding_effect_income">Einnahmen/Kosten pro Heimspiel</message>
    <message id="entity_stadiumbuilding_effect_income_help">Betrag wird bei jedem Heimspiel dem Verein gutgeschrieben (falls Betrag positiv) bzw. abgebucht (falls Betrag negativ).</message>
</messages>

=== astroChasqui/websoccer_es/modules/fireplayer/messages_en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../messages.dtd">
<messages>
    <message id="fireplayer_button">Dismiss</message>
    
    <message id="fireplayer_modal_title">Really fire this player?</message>
    <message id="fireplayer_modal_content">Do you really want to resign %s's contract?</message>
    <message id="fireplayer_modal_confirm">Yes, lay him off</message>
    
    <message id="fireplayer_modal_compensation">The player demands a compensation of <strong>%s %s</strong>!</message>
    <message id="fireplayer_tooexpensive">You cannot pay the requested compensation at the moment.</message>
    
    <message id="fireplayer_success">The player has been successfully layed off.</message>
    
    <message id="fireplayer_compensation_subject">Compensation for loss of job</message>
    
</messages>

=== astroChasqui/websoccer_es/modules/cups/messages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../messages.dtd">
<messages>
    <message id="cup_firstround_only_date">Datum</message>
    <message id="cup_firstround">Hinspiel</message>
    <message id="cup_secondround">Rückspiel</message>
    <message id="cup_created_from_winners_of_round">Gewinner aus <strong>%s</strong>.</message>
    <message id="cup_created_from_loosers_of_round">Verlierer aus <strong>%s</strong>.</message>
    <message id="cup_cuproundaward_perround_subject">Prämie für Pokalrunde</message>
    <message id="cup_cuproundaward_winner_subject">Gewinn des Pokals</message>
    <message id="cup_cuproundaward_second_subject">Prämie für zweiten Platz</message>
    
    <message id="cup_title_groups">Gruppen</message>
    <message id="cup_group_noteamsavailable">Dieser Gruppe wurden noch keine Teams zugeteilt.</message>
    <message id="cup_group_select_group_placeholder">Bitte wählen Sie eine Gruppe aus.</message>
    
</messages>

=== astroChasqui/websoccer_es/modules/leagues/messages_en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../messages.dtd">
<messages>
    <message id="leagues_navlabel">Leagues</message>
    <message id="leagues_title">Tables</message>
    
    <message id="league_navlabel">Table</message>
    
    <message id="leaguetable_block_title">Latest Table</message>
    <message id="leaguetable_block_noteamsavailable">There are no teams in this league.</message>
    
    <message id="leaguetable_head_place">Position</message>
    <message id="leaguetable_head_place_abbr">P</message>
    <message id="leaguetable_head_club">Club</message>
    <message id="leaguetable_head_matches">Matches</message>
    <message id="leaguetable_head_matches_abbr">M</message>
    <message id="leaguetable_head_wins">Wins</message>
    <message id="leaguetable_head_wins_abbr">W</message>
    <message id="leaguetable_head_draws">Draws</message>
    <message id="leaguetable_head_draws_abbr">D</message>
    <message id="leaguetable_head_defeats">Losses</message>
    <message id="leaguetable_head_defeats_abbr">L</message>
    <message id="leaguetable_head_goals">Goals</message>
    <message id="leaguetable_head_goalsdiff">Goals Difference</message>
    <message id="leaguetable_head_goalsdiff_abbr">GD</message>
    <message id="leaguetable_head_score">Points</message>
    
    <message id="leaguetable_button_type">Table Type</message>
    <message id="leaguetable_button_type_total">Total Standings</message>
    <message id="leaguetable_button_type_home">Home Table</message>
    <message id="leaguetable_button_type_guest">Away Table</message>
    
    <message id="leaguetable_timedelay_info">There might be a delay in displaying the most current standings.</message>
</messages>

=== astroChasqui/websoccer_es/modules/core/entitymessages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../messages.dtd">
<messages>
	<message id="entity_admin">Administratoren</message>
	<message id="entity_admin_name">Username</message>
	<message id="entity_admin_passwort">Passwort</message>
	<message id="entity_admin_email">E-Mail</message>
	<message id="entity_admin_r_admin">Ist Administrator</message>
	<message id="entity_admin_r_adminuser">Rechte: Kann Administratoren verwalten</message>
	<message id="entity_admin_r_user">Rechte: Kann Benutzer verwalten</message>
	<message id="entity_admin_r_daten">Rechte: Kann Spieldaten verwalten</message>
	<message id="entity_admin_r_staerken">Rechte: Kann Spielerstärken sehen und bearbeiten</message>
	<message id="entity_admin_r_spiele">Rechte: Kann Spiele verwalten</message>
	<message id="entity_admin_r_news">Rechte: Kann News verwalten</message>
	<message id="entity_admin_r_kalender">Rechte: Kann Kalender verwalten</message>
	<message id="entity_admin_r_design">Rechte: Kann Design-Dateien ändern</message>
	<message id="entity_admin_r_demo"><em>Ist Demo-User</em> (kann keine Änderungen speichern)</message>
</messages>
