=== astroChasqui/websoccer_es/modules/messages.dtd
<!ELEMENT messages (message+)>

<!ELEMENT message (#PCDATA|strong|b|i|a|em|p|ul|br)*>
<!ATTLIST message id CDATA #REQUIRED>

<!ELEMENT strong (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT em (#PCDATA)>
<!ELEMENT p (#PCDATA|strong|b|i|a|em|p|ul)*>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #IMPLIED>
<!ATTLIST a target CDATA #IMPLIED>
<!ATTLIST a class CDATA #IMPLIED>

<!ELEMENT ul (li+)>
<!ELEMENT li (#PCDATA)>

<!ELEMENT br (#PCDATA)>

=== astroChasqui/websoccer_es/modules/userregistration/adminmessages_en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../messages.dtd">
<messages>
	<message id="settings_label_allow_userregistration">Allow user registration for any guest.</message> 
    <message id="settings_label_illegal_usernames">Illegal user names</message> 
    <message id="settings_label_illegal_usernames_help">comma separated</message> 
    <message id="settings_label_max_number_of_users">Maximum number of approved users</message> 
    <message id="settings_label_max_number_of_users_help">0 for unlimited</message> 
    
    <message id="settings_label_register_use_captcha">Use reCAPTCHA security code, in order to prevent Spam registrations. This requires a free registration at <a href="https://www.google.com/recaptcha/admin/create" target="_blank">www.google.com/recaptcha</a>.</message> 
    
    <message id="settings_label_register_captcha_publickey">Public Key</message>
    <message id="settings_label_register_captcha_publickey_help">Take this key from the reCAPTCHA-registration confirmation.</message>
    <message id="settings_label_register_captcha_privatekey">Private Key</message>
    <message id="settings_label_register_captcha_privatekey_help">Take this key from the reCAPTCHA-registration confirmation.</message>

	<message id="settings_label_registration_url">Registration URL</message>
	<message id="settings_label_registration_url_help">If users must register their account at a different website, you can specify the URL to the registration form here.</message>
</messages>

=== astroChasqui/websoccer_es/modules/freeclubs/messages_es.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "../messages.dtd">
<messages>
    <message id="freeclubs_navlabel">Libres</message>
    <message id="freeclubs_title">Equipos sin Manager</message>
    <message id="freeclubs_no_free_clubs_available">Actualmente no hay clubes libres.</message>
    <message id="freeclubs_head_choose">Selección</message>
    <message id="freeclubs_button_choose">Seleccione Equipo</message>
    <message id="freeclubs_button_choose_another">Escoja otro equipo</message>
    <message id="freeclubs_msg_success">¡Felicitaciones! Usted es ahora Manager del equipo seleccionado.</message>
    <message id="freeclubs_msg_error">El equipo probablemente ya esta asignado a otro usuario.</message>
    <message id="freeclubs_msg_error_user_is_already_manager">Tú ya eres manager de un equipo.</message>
    <message id="freeclubs_msg_error_max_number_of_teams">Usted no puede manejar más de %d equipos en este momento</message>
    <message id="freeclubs_msg_error_no_club_from_same_league">Usted no puede manejar varios equipos de la misma liga.</message>
    <message id="freeclubs_msg_error_minhighscore">Es necesario un mejor puntaje de al menos %d  con el fin de gestionar un equipo adicional.</message>
</messages>

=== astroChasqui/websoccer_es/modules/formation/messages_es.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "../messages.dtd">
<messages>
    <message id="formation_navlabel">Alineación</message>
    <message id="formation_title">Alineación y Tácticas</message>
    
    <message id="next_match_block_title">Próximo Partido</message>
    <message id="next_match_block_previous_matches">Últimos Partidos</message>
    <message id="next_match_block_no_previous_matches">Es la primera vez que juega contra este equipo.</message>
    <message id="next_match_block_no_nextmatch">Actualmente no hay ningún partido programado para usted.</message>
    
    <message id="formation_playground_title">Establecer Alineación</message>
    <message id="formation_team_title">Tu Equipo</message>
    <message id="formation_team_noplayers">No hay jugadores disponibles.</message>
    <message id="formation_bench">Banquillo</message>
    
    <message id="formation_team_collapsehead_tooltip">Expandir o contraer la lista</message>
    
    <message id="formation_team_blocked_cards">Bloqueado debido a las tarjetas rojas o amarillas</message>
    <message id="formation_team_blocked_injured">El Jugador esta lesionado</message>
    
    <message id="formation_dragging_note_title">Instrucciones:</message>
    <message id="formation_dragging_note">Arrastra los jugadores sobre el campo de juego con el fin de ajustarlos para el partido.</message>
    
    <message id="formation_substitutions_title">Sustituciones</message>
    <message id="formation_substitutions_out">Fuera</message>
    <message id="formation_substitutions_in">Dentro</message>
    <message id="formation_substitutions_minute">Minuto</message>
    
    <message id="formation_substitutions_condition">Condición</message>
    <message id="formation_substitutions_condition_none">Ninguna</message>
    <message id="formation_substitutions_condition_tie">empatando</message>
    <message id="formation_substitutions_condition_leading">minutos más importantes</message>
    <message id="formation_substitutions_condition_deficit">al final del partido</message>
    
    <message id="formation_substitutions_position">Posición</message>
    <message id="formation_substitutions_position_default">(Posición principal del jugador)</message>
    
    <message id="formation_err_player_already_set">Este jugador ya está establecido.</message>
    <message id="formation_err_already_enough_players">Ya hay 11 jugadores establecidos.</message>
    <message id="formation_err_only_one_goaly_allowed">Sólo un portero permitido.</message>
    <message id="formation_err_only_x_players_per_area_allowed">Usted no debe establecer más de {0} jugadores por zona.</message>
    <message id="formation_err_only_x_players_on_bench_allowed">No más de {0} jugadores en el banquillo permitido.</message>
    <message id="formation_err_no_goaly_set">No eligió ningún portero.</message>
    <message id="formation_err_not_enough_players">Menos de 11 jugadores no esta permitido.</message>
    <message id="formation_tooltip_remove_player">Doble click para eliminar {0}</message>
    
    <message id="formation_err_nonextmatch">No hay un partido todavía.</message>
    <message id="formation_err_invalidplayer">Jugadores no válidos establecidos.</message>
    <message id="formation_err_duplicateplayer">Algunos jugadores establecidos varias veces.</message>
    <message id="formation_err_blockedplayer">Jugadores lesionados o bloqueados establecidos.</message>
    
    <message id="formation_err_invalidsubstitutionminute">Se le permite sustituir a los jugadores sólo entre el segundo 0 y 90 minutos.</message>
    
    <message id="formation_offensive_title">Juego ofensivo</message>
    
    <message id="formation_setup_title">Disposición</message>
    
    <message id="formation_bench_placeholder">Arrastrar jugador aquí...</message>
    <message id="formation_bench_sub_in">Sustituir</message>
    <message id="formation_bench_sub_title">Sustitución del jugador</message>
    
    <message id="formation_setup_button">Establecer</message>
    <message id="formation_setup_strongest">Jugadores más fuertes</message>
    <message id="formation_setup_freshest">Jugadores más frescos</message>
    <message id="formation_setup_motivated">Jugadores más motivados</message>
    
    <message id="formation_setup_altered_warn_title">¡La configuración seleccionada ha sido alterada por el sistema!</message>
    <message id="formation_setup_altered_warn_details">Su configuración no consiste en 10 jugadores de campo, por lo tanto, el sistema automáticamente modificado su selección.</message>

	<message id="formation_clearall">Borrar todo</message>
	
	<message id="formation_switch_on">Si</message>
	<message id="formation_switch_off">No</message>
	
	<message id="formation_option_longpasses">Pases Largos</message>
	<message id="formation_option_longpasses_help">Puede conducir a más tiros de gol, pero también a más pérdidas de balón.</message>
	
	<message id="formation_option_counterattacks">Contraataques</message>
	<message id="formation_option_counterattacks_help">Puede prevenir intentos de gol del oponente, sino que también reduce el número de los propios intentos.</message>
	
	<message id="formation_freekickplayer">Lanzador de Faltas</message>
	
	<message id="formation_templatename_field">Nombre de la plantilla</message>
	<message id="formation_templatename_field_help">Proporcione un nombre con el fin de salvar a esta formación, además, como plantilla.</message>
	
	<message id="formation_load_from_template">Cargar Plantilla</message>
	<message id="formation_load_from_template_none_available">No hay plantillas disponibles. Puede crear una nueva plantilla, proporcionando un nombre de plantilla cuando se guarda una nueva formación.</message>
	
	<message id="formation_template_saving_failed_because_boundary_title">Usted puede tener sólo hasta %d plantillas guardadas.</message>
	<message id="formation_template_saving_failed_because_boundary_details">Esta formación no se ha guardado como plantilla. Eliminar las plantillas sin usar.</message>
	
	<message id="formation_submitted_tooltip">Formación Enviada</message>
	<message id="formation_notsubmitted_tooltip">Formación no enviada todavía</message>
</messages>

=== astroChasqui/websoccer_es/modules/clubslogo/messages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "../messages.dtd">
<messages>
    <message id="upload-clublogo_navlabel">Neues Vereinslogo hochladen</message>
    
    <message id="upload-clublogo_intro">Sie können hier ein PNG- oder JPEG-Bild hochladen. Es muss <strong>rechteckig</strong> sein mit einer Mindestbreite von <strong>120 Pixel</strong> und einer maximalen Dateigrösse von <strong>%d KBytes</strong>.</message>
	<message id="upload-clublogo_success">Das neue Vereinslogo wurde erfolgreich hochgeladen!</message>
	
	<message id="activitylog_upload-club-picture">%s hat ein neues Vereinslogo hochgeladen.</message>
    
</messages>

=== astroChasqui/websoccer_es/modules/transferoffers/messages_en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../messages.dtd">
<messages>
    
    <message id="transferoffer_button">Offer to buy</message>
    
    <message id="transferoffer_modal_title">Transfer Offer</message>
    
    <message id="transferoffer_label_amount">Amount</message>
    <message id="transferoffer_label_comment">Comment</message>
    <message id="transferoffer_label_fieldset_playerexchange">Player Exchange (optional)</message>
    <message id="transferoffer_label_exchangeplayer1">Player</message>
    <message id="transferoffer_label_exchangeplayer2">2nd Player</message>
    
    <message id="transferoffer_label_fieldset_contract">Contractual Terms</message>
    
    <message id="transferoffer_err_ownplayer">The player is already in your team.</message>
    <message id="transferoffer_err_nomanager">The player's team has currently no manager. Hence, offers to buy cannot be processed.</message>
    <message id="transferoffer_err_unsellable">The player has been either marked as unsellable or is on the transfermarket.</message>
    
    <message id="transferoffer_err_open_offers_exist">The player's manager still has open offers from you. You can have only one offer at the same time with the same manager. Wait until the other user has processed your other offer or cancel it.</message>
    
    <message id="transferoffer_err_noalternative_allowed">The player's manager does not want any new offer from you for this player.</message>
    
    <message id="transferoffer_err_transferstop">The player must not change the team due to a transfer stop of %d days.</message>
    
    <message id="transferoffer_err_exchangeplayer_on_transfermarket">The selected player, %s, is currently on the transfer market. Hence, he cannot be selected for a player exchange.</message>
    <message id="transferoffer_err_exchangeplayer_involved_in_other_offers">The selected player, %s, has been already offered in another open tranfer offer. Cancel your other offer or choose a different player.</message>
	<message id="transferoffer_err_exchangeplayer_transferstop">The selected player, %s, must not change the team due to an active tranfer stop.</message>
    
	<message id="transferoffer_err_totaloffers_too_high">Your budget is not enough for this offer. Reduce your offer or cancen other open requests.</message>

	<message id="transferoffer_err_salary_too_high">You currently cannot afford this player's salary.</message>
	
	<message id="transferoffer_submitted_title">Your offer has been successfully submitted!</message>
	<message id="transferoffer_submitted_message">The player's manager got a notification and will need to accept or reject your offer.</message>


	<message id="transferoffers_navlabel">Transfer Offers</message>
	<message id="transferoffers_tab_received">Received Offers</message>
	<message id="transferoffers_tab_sent">Sent Offers</message>
	
	<message id="transferoffers_no_received_offers">You have not received any offers from other managers, yet.</message>
	<message id="transferoffers_no_sent_offers">There are currently no offers from you.</message>
	
	<message id="transferoffers_offer_reaction">Reaction</message>
	<message id="transferoffers_offer_reaction_accept">Accept</message>
	<message id="transferoffers_offer_reaction_reject">Reject</message>
	<message id="transferoffers_offer_status_adminapprovalpending">Approval pending</message>
	<message id="transferoffers_offer_status_rejected">rejected</message>
	
	<message id="transferoffers_offer_showcomment">Show comment</message>
	<message id="transferoffers_offer_comment_title">%s wrote:</message>
	
	<message id="transferoffer_accepted_title">The offer is accepted!</message>
	<message id="transferoffer_accepted_message">The player changed the team successfully.</message>
	<message id="transferoffer_accepted_message_approvalpending">Note that the manual approval by an administrator is pending now.</message>

	<message id="transferoffer_accept_err_exchangeplayer_on_transfermarket">The offered exchange player %s has been put on the tranfer market. Hence, the transfer cannot be executed at the moment.</message>
	<message id="transferoffer_accept_err_exchangeplayer_notinteam">The offered exchange player %s is not in the sender's team anymore. This transfer is not possible.</message>
	<message id="transferoffer_accept_err_exchangeplayer_salarytoohigh">You cannot afford %s's salary at the moment.</message>

	<message id="transferoffers_sent_cancellation">Cancellation</message>
	<message id="transferoffers_offer_cancellation_button">Cancel</message>
	<message id="transferoffers_offer_cancellation_notfound">The offer has been deleted or already executed.</message>
	<message id="transferoffers_offer_cancellation_success">The offer has been successfully canceled.</message>
	
	<message id="transferoffer_reject_modal_title">Reject offer</message>
	<message id="transferoffer_reject_label_comment">Reason (optional)</message>
	<message id="transferoffer_reject_label_allow_alternative">The user may send another alternative offer.</message>
	<message id="transferoffers_offer_reject_success">The offer has been succesfully rejected.</message>
	
	<message id="directtransfer_subject">Player Transer</message>
	
	<message id="transferoffer_notification_offerreceived"><strong>{sendername}</strong> sent you a player transfer offer.</message>
	<message id="transferoffer_notification_executed">The agreed transfer of <strong>{playername}</strong> has been executed.</message>
	<message id="transferoffer_notification_rejected"><strong>{receivername}</strong> rejected your transfer offer for <strong>{playername}</strong>.</message>
</messages>

=== astroChasqui/websoccer_es/modules/users/adminmessages_en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "../messages.dtd">
<messages>
    <message id="settings_tab_users">Users</message> 
    
	<message id="popup_user_inactivity_total">Total</message>
	<message id="popup_user_inactivity_title_action">Measured Action</message>
	
	<message id="settings_label_highscore_win">Highscore per Win</message>
	<message id="settings_label_highscore_loss">Highscore per Loss</message>
	<message id="settings_label_highscore_draw">Highscore per Draw</message>
	
	<message id="settings_label_user_picture_upload_enabled">Users may upload their own profile picture.</message>
	
	<message id="settings_label_user_picture_upload_maxsize_kb">Picture upload: Maximum size</message>
	<message id="settings_label_user_picture_upload_maxsize_kb_help">in KBytes</message>
	
</messages>

=== astroChasqui/websoccer_es/modules/users/messages_en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "../messages.dtd">
<messages>
	<message id="highscore_navlabel">Highscore</message>
	<message id="highscore_title">Users Highscore Ranking</message>
	
	<message id="highscore_rank">Rank</message>
	<message id="highscore_user">User</message>
	<message id="highscore_registration_date">Registration Date</message>
	<message id="highscore_score">Score</message>
	
	<message id="user_navlabel">User Profile</message>
	
	<message id="user_tab_profile">Profile</message>
	
	<message id="user_visit_website">visit</message>
	
	<message id="user_changepicture_button">Upload picture</message>
	
	<message id="history_tab">History</message>
	<message id="history_no_records">The user has not completed any season, yet.</message>
</messages>

=== astroChasqui/websoccer_es/modules/youth/messages_en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../messages.dtd">
<messages>
    <message id="youth-team_navlabel">Youth Team</message>
    <message id="youth-scouting_navlabel">Scouting</message>
    <message id="youth-matchrequests_navlabel">Match Requests</message>
    <message id="youth-matches_navlabel">Matches</message>
    <message id="youth-marketplace_navlabel">Marketplace</message>
    
    <message id="youthteam_title">My Youth Team</message>
    <message id="youthteam_no_players">There are currently no players in your youth team.</message>
    <message id="youthteam_scout_button">Scout for new talents</message>
    
    <message id="youthteam_showstatistics_tooltip">Show or collapse statistics</message>
    
    <message id="youthteam_min_age_info">A player must be at least %d years old in order to be moved to the professional team.</message>
    
    <message id="youthteam_action_make_professional">Transfer to professional team</message>
    <message id="youthteam_action_sell">Offer in marketplace</message>
    <message id="youthteam_action_fire">Dismiss</message>
    <message id="youthteam_action_removefrommarket">Offered for transfer. Remove from market.</message>
    <message id="youthteam_action_buy">Buy</message>
    
    <message id="youthplayer-sell_navlabel">Offer youth player in public market</message>
    <message id="youthplayer-sell_formlabel">Enter your desired transfer fee</message>
    
    <message id="youthteam_err_notownplayer">The player does not belong to your team (anymore).</message>
    <message id="youthteam_sell_err_alreadyonmarket">The player is already on the marketplace.</message>
    
    <message id="youthteam_sell_success">The player can now be bought by other managers.</message>
    <message id="youthteam_removefrommarket_success">The player has been removed from the marketplace.</message>
    <message id="youthteam_fire_success">The player got dismissed.</message>
    <message id="youthteam_buy_success">The player belongs to your team now!</message>
    
    <message id="youthplayer-fire_navlabel">Dismiss youth player</message>
    <message id="youthplayer-fire_formlabel">Remove from team</message>
    <message id="youthplayer-fire_confirmationmsg">Do you really want to lay off this player? This cannot be undone later.</message>

    <message id="youthplayer-buy_navlabel">Buy youth player</message>
    <message id="youthplayer-buy_formlabel">Hire this player</message>
    <message id="youthplayer-buy_confirmationmsg">Do you really want to buy this player? He will be immediately transferred to your team for the above mentioned transfer fee.</message>
    
    <message id="youthteam_buy_err_ownplayer">The player already belongs to your team.</message>
    <message id="youthteam_buy_err_ownplayer_otherteam">You cannot buy players from one of your other teams.</message>
    <message id="youthteam_buy_err_notenoughbudget">You cannot afford the transfer fee at the moment.</message>
    
	<message id="team_details_tab_youthplayers">Youth Team</message>
	<message id="youthteam_no_players_in_team">This team has currently no youth players.</message>
	
	<message id="youthteam_transferfee_subject">Transfer fee for youth player</message>
    <message id="youthteam_transfer_notification">The youth player <strong>{player}</strong> is now playing for <strong>{newteam}</strong>.</message>

	<message id="youthplayer-makeprofessional_navlabel">Hire as professional</message>
	<message id="youthplayer-makeprofessional_formlabel">Move to professional team</message>
	<message id="youthplayer-makeprofessional_form_intro">Select the player's main position. <strong>Note:</strong> This cannot be changed later.</message>
    
	<message id="youthteam_makeprofessional_err_tooyoung">The player's age must be at least %d years.</message>
	<message id="youthteam_makeprofessional_err_invalidmainposition">You selected an invalid main position.</message>
	<message id="youthteam_makeprofessional_err_budgettooless">You cannot pay the player's salary at the moment.</message>
	
	<message id="youthteam_makeprofessional_success">The player now belongs to the professional team!</message>
	
	<message id="youthteam_scouting_lastexecution">Last Scouting</message>
	<message id="youthteam_scouting_lastexecution_never">Never executed before</message>
	<message id="youthteam_scouting_nextpossibleexecution">The next scouting is earliest possible on %s</message>
	
	<message id="youthteam_scouting_schoosescout">Choose your favourite scout</message>
	<message id="youthteam_scouting_noscoutavailable">There is no scout available at the moment.</message>
	<message id="youthteam_scouting_schoosecountry">At which country shall be searched for new talents?</message>
	
	<message id="youthteam_scouting_err_breakviolation">The earliest date to scout next time would be: %s</message>
	<message id="youthteam_scouting_err_invalidcountry">It is not possible to scout at the selected country. Please contact the administrator.</message>
	<message id="youthteam_scouting_err_invalidscout">The selected scout does not exist (anymore).</message>
	<message id="youthteam_scouting_err_notenoughbudget">You cannot afford the scout's fee at the moment.</message>
	
	<message id="youthteam_scouting_fee_subject">Fee for youth player scouting</message>
	<message id="youthteam_scouting_failure">Unfortunately, the scout has not found any talented player during his trip.</message>
	
	<message id="youthteam_scouting_success">Congratulation! The scout could find a new talent.</message>
	<message id="youthteam_scouting_success_details">Please welcome %s in your youth team!</message>
	
	<message id="youthteam_matchrequest_createnew">Post new request</message>
	<message id="youthteam_matchrequest_none_available">There are no open match requests at the moment.</message>
	<message id="youthteam_matchrequest_accept">Accept</message>
	<message id="youthteam_matchrequest_cancel">Cancel</message>
	
	<message id="youth-matchrequests-create_navlabel">Post a new youth match request</message>
	<message id="youthteam_matchrequest_create_date">Date and time</message>
	<message id="youthteam_matchrequest_reward">Reward</message>
	
	<message id="youthteam_matchrequest_create_err_invaliddate">The entered date is invalid. If you have used the form properly, then contact an administrator, please.</message>
	<message id="youthteam_matchrequest_create_err_too_many_open_requests">You may have only up to %d open match requests. Cancel your other requests or wait until they are expired.</message>
	<message id="youthteam_matchrequest_create_err_budgetnotenough">You cannot afford the entered reward at the moment.</message>
	<message id="youthteam_matchrequest_create_err_notenoughplayers">You do not have enough youth players in order to attend matches.</message>
	
	<message id="youthteam_matchrequest_create_success">Your match request has been successfully published.</message>
	
	<message id="youthteam_matchrequest_cancel_err_notfound">The match request does not exist (anymore). It might have been accepted already.</message>
	<message id="youthteam_matchrequest_cancel_success">The match request has been succesfully cancelled.</message>
	
	<message id="youthteam_matchrequest_accept_err_ownrequest">You cannot play against yourself.</message>
	
	<message id="youthteam_matchrequest_err_maxperday_violated">You can have only %d youth match(es) per day.</message>
	
	<message id="youthteam_matchrequest_accept_success">The match has been successfully created!</message>
	<message id="youthteam_matchrequest_accept_success_details">Set your tactics for this match now.</message>
	
	<message id="youthteam_matchrequest_reward_subject">Reward for accepting a youth match request</message>
	<message id="youthteam_matchrequest_accept_notification">The team <strong>{team}</strong> has accepted your youth match request from {date}.</message>

	<message id="youthmatches_title">Matches of my team</message>
	<message id="youthmatches_no_matches">There haven't been any matches with your team so far.</message>
	
	<message id="youthmarketplace_no_players">No youth players are for sale at the moment.</message>
	
	<message id="youth-formation_navlabel">Formation</message>
	<message id="youthformation_err_matchexpired">You cannot set a formation for this match anymore, because it is either already simulated or will be simulated shortly.</message>

	<message id="youthteam_salarypayment_subject">Youth players' salary</message>
	
	<message id="youth-match_navlabel">Youth Match</message>
	<message id="youthmatch_statistic_avg_strength">Average Strength</message>
	
	<message id="ymreport_goal"><strong>Goal by {scorer}!</strong></message>
	<message id="ymreport_attempt">{scorer} takes a shot at the goal.</message>
	<message id="ymreport_tackle">Tackle between {winner} and {loser}. {winner} wins!</message>
	<message id="ymreport_injury">{player} is injured and must leave the pitch.</message>
	<message id="ymreport_card_yellowred">{player} gets the yellow-red card.</message>
	<message id="ymreport_card_yellow">{player} gets a yellow card.</message>
	<message id="ymreport_card_red">{player} gets a red card and must leave the pitch.</message>
	<message id="ymreport_penalty_success"><strong>{player} converts a penalty kick!</strong></message>
	<message id="ymreport_penalty_failure"><em>{player} misses a penalty!</em></message>
	<message id="ymreport_substitution">Substitution! <strong>{in}</strong> replaces <strong>{out}</strong>.</message>
</messages>
