=== astroChasqui/websoccer_es/modules/messages.dtd
<!ELEMENT messages (message+)>

<!ELEMENT message (#PCDATA|strong|b|i|a|em|p|ul|br)*>
<!ATTLIST message id CDATA #REQUIRED>

<!ELEMENT strong (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT em (#PCDATA)>
<!ELEMENT p (#PCDATA|strong|b|i|a|em|p|ul)*>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #IMPLIED>
<!ATTLIST a target CDATA #IMPLIED>
<!ATTLIST a class CDATA #IMPLIED>

<!ELEMENT ul (li+)>
<!ELEMENT li (#PCDATA)>

<!ELEMENT br (#PCDATA)>

=== astroChasqui/websoccer_es/modules/cups/entitymessages_en.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "../messages.dtd">
<messages>
    <message id="entity_cup">Cup</message>
    
	<message id="entity_cup_name">Name</message>
	<message id="entity_cup_winner_id">Winner</message>
	<message id="entity_cup_matches">Matches</message>
	<message id="entity_cup_rounds">Rounds</message>
	<message id="entity_cup_logo">Logo</message>
	<message id="entity_cup_winner_award">Winner award</message>
	<message id="entity_cup_second_award">Award for second</message>
	<message id="entity_cup_perround_award">Award per round</message>
	<message id="entity_cup_archived">archived</message>
</messages>

=== astroChasqui/websoccer_es/modules/formation/messages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "../messages.dtd">
<messages>
    <message id="formation_navlabel">Aufstellung</message>
    <message id="formation_title">Aufstellung und Taktik</message>
    
    <message id="next_match_block_title">Nächstes Spiel</message>
    <message id="next_match_block_previous_matches">Vorherige Begegnungen</message>
    <message id="next_match_block_no_previous_matches">Sie spielen zum ersten mal gegen diese Mannschaft.</message>
    
    <message id="next_match_block_no_nextmatch">Im Moment ist noch kein Spiel für Sie angesetzt.</message>
    
    <message id="formation_playground_title">Aufstellung setzen</message>
    <message id="formation_team_title">Ihr Kader</message>
    <message id="formation_team_noplayers">Es stehen keine Spieler zur Verfügung.</message>
    <message id="formation_bench">Bank</message>
    
    <message id="formation_team_collapsehead_tooltip">Liste auf- oder zuklappen</message>
    
    <message id="formation_team_blocked_cards">Gelb- oder Rotsperre</message>
    <message id="formation_team_blocked_injured">Spieler ist verletzt</message>
    
    <message id="formation_dragging_note_title">Hinweis zur Nutzung:</message>
    <message id="formation_dragging_note">Ziehen Sie Spieler auf das Feld, um sie aufzustellen oder doppelklicken Sie auf den Spieler.</message>
    
    <message id="formation_substitutions_title">Auswechslungen</message>
    <message id="formation_substitutions_out">Raus</message>
    <message id="formation_substitutions_in">Rein</message>
    <message id="formation_substitutions_minute">Minute</message>
    
    <message id="formation_substitutions_condition">Bedingung</message>
    <message id="formation_substitutions_condition_none">Keine</message>
    <message id="formation_substitutions_condition_tie">bei Gleichstand</message>
    <message id="formation_substitutions_condition_leading">bei Führung</message>
    <message id="formation_substitutions_condition_deficit">bei Rückstand</message>
    
    <message id="formation_substitutions_position">Position</message>
    <message id="formation_substitutions_position_default">(Hauptposition des Spielers)</message>
    
    <message id="formation_err_player_already_set">Der Spieler ist bereits aufgestellt.</message>
    <message id="formation_err_already_enough_players">Es stehen bereits 11 Spieler auf dem Platz.</message>
    <message id="formation_err_only_one_goaly_allowed">Es darf maximal nur ein Torwart aufgestellt werden.</message>
    <message id="formation_err_only_x_players_per_area_allowed">Es dürfen maximal nur jeweils bis zu {0} Feldspieler pro Bereich aufgestellt werden.</message>
    <message id="formation_err_only_x_players_on_bench_allowed">Es dürfen nur maximal {0} Ersatzspieler auf der Bank sitzen.</message>
    <message id="formation_err_no_goaly_set">Es wurde kein Torwart aufgestellt.</message>
    <message id="formation_err_not_enough_players">Es stehen nicht genau 11 Spieler auf dem Platz.</message>
    <message id="formation_tooltip_remove_player">Doppelklick um {0} zu entfernen</message>
    
    <message id="formation_err_nonextmatch">Das nächste Spiel steht noch nicht fest.</message>
    <message id="formation_err_invalidplayer">Es wurden ungültige Spieler aufgestellt.</message>
    <message id="formation_err_duplicateplayer">Es wurden Spieler doppelt aufgestellt.</message>
    <message id="formation_err_blockedplayer">Es wurden gesperrte oder verletzte Spieler aufgestellt.</message>
    
    <message id="formation_err_invalidsubstitutionminute">Es darf nur zwischen der zweiten und 90. Minute ausgewechselt werden.</message>
    
    <message id="formation_offensive_title">Offensiv spielen</message>
    
    <message id="formation_setup_title">Formation</message>
    
    <message id="formation_bench_placeholder">Spieler hier hinziehen...</message>
    <message id="formation_bench_sub_in">Einwechseln</message>
    <message id="formation_bench_sub_title">Spielerwechsel</message>
    
    <message id="formation_setup_button">Aufstellen</message>
    <message id="formation_setup_strongest">Stärkste Spieler</message>
    <message id="formation_setup_freshest">Frischeste Spieler</message>
    <message id="formation_setup_motivated">Motivierteste Spieler</message>
    
    <message id="formation_setup_altered_warn_title">Die angegebene Formation wurde vom System angepasst!</message>
    <message id="formation_setup_altered_warn_details">Ihre gewählte Formation umfasst nicht genau 10 Feldspieler, weshalb das System Ihre Auswahl automatisch korrigiert hat.</message>

	<message id="formation_clearall">Spielfeld leeren</message>
	
	<message id="formation_switch_on">Ein</message>
	<message id="formation_switch_off">Aus</message>
	
	<message id="formation_option_longpasses">Lange Pässe</message>
	<message id="formation_option_longpasses_help">Kann zu mehr Torschüssen führen, aber auch zu mehr Ballverlusten.</message>
	
	<message id="formation_option_counterattacks">Konterspiel</message>
	<message id="formation_option_counterattacks_help">Kann Gegenangriffe verhindern, aber reduziert auch die Anzahl an eigenen Torchancen.</message>
	
	<message id="formation_freekickplayer">Freistoß- und Eckballschütze</message>
	
	<message id="formation_templatename_field">Vorlagenname</message>
	<message id="formation_templatename_field_help">Geben Sie einen Namen an, um diese Aufstellung zusätzlich als Vorlage abzuspeichern.</message>
	<message id="formation_load_from_template">Vorlage laden</message>
	<message id="formation_load_from_template_none_available">Es stehen keine Vorlagen zur Verfügung. Eine neue Vorlage erstellen Sie indem Sie einen Vorlagennamen beim Speichern einer neuen Aufstellung angeben.</message>
	
	<message id="formation_template_saving_failed_because_boundary_title">Sie dürfen nur %d Vorlagen speichern!</message>
	<message id="formation_template_saving_failed_because_boundary_details">Die Aufstellung wurde nicht als Vorlage abgelegt. Löschen Sie zuerst nicht mehr benötigte Vorlagen.</message>
	
	<message id="formation_submitted_tooltip">Aufstellung wurde abgegeben</message>
	<message id="formation_notsubmitted_tooltip">Noch keine Aufstellung abgegeben</message>
</messages>

=== astroChasqui/websoccer_es/modules/users/adminmessages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "../messages.dtd">
<messages>
    <message id="settings_tab_users">Benutzer</message> 
    
	<message id="popup_user_inactivity_total">Gesamt</message>
	<message id="popup_user_inactivity_title_action">Gemessene Tätigkeit</message>
	
	<message id="settings_label_highscore_win">Highscore pro Sieg</message>
	<message id="settings_label_highscore_loss">Highscore pro Niederlage</message>
	<message id="settings_label_highscore_draw">Highscore pro Unentschieden</message>
	
	<message id="settings_label_user_picture_upload_enabled">Benutzer dürfen ein eigenes Profilbild hochladen.</message>
	
	<message id="settings_label_user_picture_upload_maxsize_kb">Bildupload: Maximalgrösse</message>
	<message id="settings_label_user_picture_upload_maxsize_kb_help">in KBytes</message>
	
</messages>

=== astroChasqui/websoccer_es/modules/userregistration/messages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../messages.dtd">
<messages>
    <message id="register_navlabel">Registrieren</message>
    <message id="registration_disabled">Die Benutzeranmeldung ist derzeit durch den Administrator deaktiviert.</message>
    <message id="registration_title">Als Benutzer registrieren</message>
    <message id="registration_password_repeat">Passwort wiederholen</message>
    <message id="registration_email_repeat">E-Mail wiederholen</message>
    <message id="registration_submit_button">Registrieren</message>
    
    <message id="registration_illegal_username">Der angegebene Benutzername ist nicht erlaubt.</message>
    <message id="registration_repeated_password_notmatching">Das wiederholte Passwort stimmt nicht mit dem zuerst eingegebenen Passwort überein.</message>
    <message id="registration_repeated_email_notmatching">Die wiederholte E-Mail-Adresse stimmt nicht mit der zuerst eingegebenen Adresse überein.</message>
    <message id="registration_user_exists">Der Benutzername oder die E-Mail-Adresse ist bereits vergeben.</message>
    <message id="registration_max_number_users_exceeded">Im Moment können sich keine weiteren Benutzer registrieren.</message>
    
    <message id="registration_invalidcaptcha">Der Sicherheitscode ("Captcha") wurde falsch eingegeben.</message>
    
    
    <message id="register-success_navlabel">Registrierung abgeschickt</message>
    <message id="register-success_message_title">Registrierung abgeschickt - Prüfen Sie Ihre E-Mails</message>
    <message id="register-success_message_content">Zur Überprüfung auf die Echtheit der von Ihnen angegebenen E-Mail-Adresse wurde Ihnen vom System automatisch eine E-Mail mit Aktivierungslink geschickt.</message>
	<message id="register-success_nextstep">Rufen Sie nun Ihre E-Mails ab und folgen Sie den Anweisungen in der von uns versendeten E-Mail. Es kann passieren, dass die E-Mail etwas zeitversetzt ankommt.</message>
    
	<message id="activation_email_subject">Vervollständigung Ihrer Registrierung</message>
	<message id="activation_email_greeting">Guten Tag,</message>
	<message id="activation_email_introduction">zur Vervollständigung Ihrer Benutzerregistrierung rufen Sie bitte folgende Internetadresse auf:</message>
	<message id="activation_email_ending">Wenn Sie sich nicht bei uns registriert haben und einen Missbrauch Ihrer E-Mail-Adresse vermuten, antworten Sie bitte auf diese E-Mail.</message>
	
</messages>

=== astroChasqui/websoccer_es/modules/userabsence/messages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "../messages.dtd">
<messages>
    <message id="absence_navlabel">Abwesenheit</message>
    <message id="absence_intro">Fahren Sie in den Urlaub oder können aus anderen Gründen für eine kurze Zeit nicht am Spiel teilnehmen? Melden Sie sich hier als abwesend und geben Sie einen Stellvertreter an. Dieser kann dann Ihre Teams führen bis Sie wieder anwesend sind.</message>
    
    <message id="absence_label_days">Tage</message>
    <message id="absence_label_days_help">(voraussichtlich)</message>
    
    <message id="absence_err_invaliddeputy">Es konnte kein Benutzer mit dem eingegebenen Namen gefunden werden. Überprüfen Sie die Schreibweise.</message>
    <message id="absence_err_deputyisself">Sorry, Sie dürfen sich leider nicht selbst vertreten.</message>
    
    <message id="absence_report_success">Erfolgreich als abwesend gemeldet!</message>
    
    <message id="absence_reportinfo">Sie sind bis zum %s als abwesend gemeldet. Ihr Stellvertreter ist <strong>%s</strong>.</message>
    <message id="absence_return_button">Ich bin wieder zurück</message>
    <message id="absence_return_success">Sie können Ihre Teams wieder managen!</message>
    
    <message id="absence_warning">Sie gelten derzeit als abwesend und können daher Ihre Teams nicht managen.</message>
    
    <message id="absence_profile_info">Der Benutzer ist bis zum %s abwesend.</message>
    
    <message id="absence_notification">{user} hat sich abwesend gemeldet und Sie als Stellvertreter für seine Teams angegeben.</message>
    <message id="absence_comeback_notification">{user} hat sich aus seiner Abwesenheit zurückgemeldet und führt wieder seine Teams.</message>
</messages>

=== astroChasqui/websoccer_es/modules/leagues/entitymessages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../messages.dtd">
<messages>
	<message id="entity_league">Liga</message>
	<message id="entity_league_name">Name</message>
	<message id="entity_league_kurz">Kürzel</message>
	<message id="entity_league_land">Land</message>
	<message id="entity_league_p_steh">Durch. Auslastung Stehplätze</message>
	<message id="entity_league_p_sitz">Durch. Auslastung Sitzplätze</message>
	<message id="entity_league_p_haupt_steh">Durch. Auslastung Stehplätze (Haupttribüne)</message>
	<message id="entity_league_p_haupt_sitz">Durch. Auslastung Sitzplätze (Haupttribüne)</message>
	<message id="entity_league_p_vip">Durch. Auslastung VIP-Loge</message>
	<message id="entity_league_preis_steh">Durch. Preis für Stehplätze</message>
	<message id="entity_league_preis_sitz">Durch. Preis für Sitzplätze</message>
	<message id="entity_league_preis_vip">Durch. Preis für VIP-Logen</message>
</messages>

=== astroChasqui/websoccer_es/modules/core/messages_es.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../messages.dtd">
<messages>
	<message id="offline_title">Estamos temporalmente fuera de línea</message>
	<message id="error_action_required_team">Tienes que ser manager de un equipo con el fin de ejecutar esta acción.</message>
	
	<message id="requireslogin_box_title">Acceso denegado</message>
	<message id="requireslogin_box_message">Es necesario estar registrado para poder ver el contenido del sitio.</message>
	
	<message id="date_yesterday">Ayer</message>
	<message id="date_today">Hoy</message>
	<message id="date_tomorrow">Mañana</message>
	
	<message id="privacypolicy_navlabel">Política de privacidad</message>
</messages>

=== astroChasqui/websoccer_es/modules/stadium/adminmessages_de.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE messages SYSTEM "../messages.dtd">
<messages>
    <message id="settings_tab_stadium">Stadien</message>
    <message id="settings_label_stadium_max_side">Max. Nebentribüne</message>
	<message id="settings_label_stadium_max_side_help">Maximale Anzahl an Plätze auf den Nebentribünen.</message>
	
	<message id="settings_label_stadium_max_grand">Max. Haupttribüne</message>
	<message id="settings_label_stadium_max_grand_help">Maximale Anzahl an Plätze auf der Haupttribüne.</message>

	<message id="settings_label_stadium_max_vip">Max. VIP Logen</message>
	<message id="settings_label_stadium_max_vip_help">Maximale Anzahl an VIP-Logen.</message>
	
	<message id="settings_label_stadium_cost_standing">Ausbaukosten Stehplatz Nebentribüne</message>
	<message id="settings_label_stadium_cost_standing_help">pro Platz. Diese Kosten werden zu den individuellen Preisen der unterschiedlichen Bauträger addiert.</message>
	<message id="settings_label_stadium_cost_seats">Ausbaukosten Sitzplatz Nebentribüne</message>
	<message id="settings_label_stadium_cost_seats_help">pro Platz</message>
	<message id="settings_label_stadium_cost_standing_grand">Ausbaukosten Stehplatz Haupttribüne</message>
	<message id="settings_label_stadium_cost_standing_grand_help">pro Platz</message>
	<message id="settings_label_stadium_cost_seats_grand">Ausbaukosten Sitzplatz Haupttribüne</message>
	<message id="settings_label_stadium_cost_seats_grand_help">pro Platz</message>
	<message id="settings_label_stadium_cost_vip">Ausbaukosten VIP Loge</message>
	<message id="settings_label_stadium_cost_vip_help">pro Platz</message>
	
	<message id="settings_label_stadium_construction_delay">Bauverzögerung in Tagen</message>
	<message id="settings_label_stadium_construction_delay_help">Mögliche Verzögerung bei der Fertigstellung eines Stadionausbaus wenn ein unzuverlässiger Bauträger gewählt wurde. Sollte mindestens so hoch sein, dass bei der zukünftigen Wahl des Bauträgers auch teurere (aber dafür zuverlässigere) Anbieter interessant sind.</message>

	<message id="settings_label_stadium_hide_builders_reliability">Zuverlässigkeit von Bauträgern bei Angeboten ausblenden.</message>
	
	<message id="settings_label_stadium_maintenanceinterval_pitch">Wartungsintervall Rasen</message>
	<message id="settings_label_stadium_maintenanceinterval_pitch_help">Heimspiele. Nach wievielen Heimspielen die Rasenqualität sinkt.</message>
	
	<message id="settings_label_stadium_maintenanceinterval_videowall">Wartungsintervall Videowand</message>
	<message id="settings_label_stadium_maintenanceinterval_videowall_help">Heimspiele</message>
	
	<message id="settings_label_stadium_maintenanceinterval_seatsquality">Wartungsintervall Sitze</message>
	<message id="settings_label_stadium_maintenanceinterval_seatsquality_help">Heimspiele</message>
	
	<message id="settings_label_stadium_maintenanceinterval_vipquality">Wartungsintervall VIP Logen</message>
	<message id="settings_label_stadium_maintenanceinterval_vipquality_help">Heimspiele</message>
	
	<message id="settings_label_stadium_pitch_price">Wartungskosten Rasen</message>
	<message id="settings_label_stadium_pitch_price_help">Kosten für Ausbau zur ersten Stufe. Für weitere Stufen greift der unten angegebene Zuschlag.</message>
	
	<message id="settings_label_stadium_videowall_price">Wartungskosten Videowand</message>
	<message id="settings_label_stadium_seatsquality_price">Wartungskosten Sitze (pro Sitz)</message>
	<message id="settings_label_stadium_vipquality_price">Wartungskosten VIP Logen (pro Loge)</message>
	
	<message id="settings_label_stadium_maintenance_priceincrease_per_level">Wartungskostenzuschlag pro Stufe</message>
	<message id="settings_label_stadium_maintenance_priceincrease_per_level_help">Prozent; Kumulierter Aufschlag zu den Wartungskosten. Beispiel: 10% bedeutet einen Aufschlag von 40% bei Ausbau zu Stufe 5 (Kosten Stufe 1 + 10% + 10% + 10% + 10%). 0 für keinen Zuschlag.</message>

	<message id="settings_label_stadium_pitch_effect">Auswirkung Rasenzustand</message>
	<message id="settings_label_stadium_pitch_effect_help">Wieviel Prozentpunkte pro fehlender Stufe das eigene Team bei Heimspielen an Technikstärke verliert.</message>
	
	<message id="settings_label_stadium_videowall_effect">Auswirkung Videowand</message>
	<message id="settings_label_stadium_videowall_effect_help">Wieviel Prozentpunkte mehr Zuschauer pro Stufe zu Heimspielen kommen.</message>
	
	<message id="settings_label_stadium_seatsquality_effect">Auswirkung Sitzzustand</message>
	<message id="settings_label_stadium_seatsquality_effect_help">Wieviel Prozentpunkte weniger Zuschauer pro fehlender Stufe zu Heimspielen kommen.</message>
	
	<message id="settings_label_stadium_vipquality_effect">Auswirkung Zustand VIP Logen</message>
	<message id="settings_label_stadium_vipquality_effect_help">Wieviel Prozentpunkte weniger Zuschauer pro fehlender Stufe zu Heimspielen kommen.</message>
</messages>
