=== astroChasqui/websoccer_es/modules/module.dtd
<!ELEMENT module (admin?|settings?|pages?|dependencies?|blocks?|actions?|plugins?)*>
<!ATTLIST module version CDATA #REQUIRED>

<!ELEMENT dependencies (dependency+)>
<!ELEMENT dependency EMPTY>
<!ATTLIST dependency module CDATA #REQUIRED>
<!ATTLIST dependency version CDATA #REQUIRED>

<!ELEMENT admin (adminpage+)>

<!ELEMENT adminpage (entity?)>
<!ATTLIST adminpage id CDATA #REQUIRED>
<!ATTLIST adminpage navcategory CDATA #REQUIRED>
<!ATTLIST adminpage entity CDATA #IMPLIED>
<!ATTLIST adminpage permissionrole (r_admin|r_daten|r_adminuser|r_news|r_spiele|r_user) #IMPLIED>
<!ATTLIST adminpage filename CDATA #IMPLIED>

<!ELEMENT entity (overview, editform?)>
<!ATTLIST entity dbtable CDATA #REQUIRED>

<!ELEMENT overview (column+, join*)>
<!ATTLIST overview add (true|false) "true">
<!ATTLIST overview edit (true|false) "false">
<!ATTLIST overview delete (true|false) "false">
<!ATTLIST overview logging (true|false) "false">
<!ATTLIST overview loggingcolumns CDATA #IMPLIED>

<!ELEMENT column EMPTY>
<!ATTLIST column id CDATA #REQUIRED>
<!ATTLIST column filter (true|false) "false">
<!ATTLIST column sort (true|false) "false">
<!ATTLIST column type (text|number|email|boolean|select|timestamp|percent|fk) #REQUIRED>
<!ATTLIST column field CDATA #REQUIRED>
<!ATTLIST column selection CDATA #IMPLIED>
<!ATTLIST column converter CDATA #IMPLIED>
<!ATTLIST column hidden (true|false) "false">

<!ELEMENT join EMPTY>
<!ATTLIST join type (LEFT|INNER|RIGHT) #REQUIRED>
<!ATTLIST join jointable CDATA #REQUIRED>
<!ATTLIST join joincondition CDATA #REQUIRED>

<!ELEMENT editform (field+)>

<!ELEMENT field EMPTY>
<!ATTLIST field id CDATA #REQUIRED>
<!ATTLIST field required (true|false) "false">
<!ATTLIST field editonly (true|false) "false">
<!ATTLIST field type (text|number|email|boolean|password|url|select|textarea|file|timestamp|color|date|percent|foreign_key) #REQUIRED>
<!ATTLIST field converter CDATA #IMPLIED>
<!ATTLIST field validator CDATA #IMPLIED>
<!ATTLIST field entity CDATA #IMPLIED>
<!ATTLIST field jointable CDATA #IMPLIED>
<!ATTLIST field cascade CDATA #FIXED "delete">
<!ATTLIST field labelcolumns CDATA #IMPLIED>
<!ATTLIST field selection CDATA #IMPLIED>
<!ATTLIST field roles CDATA #IMPLIED>
<!ATTLIST field readonly (true|false) "false">
<!ATTLIST field default CDATA #IMPLIED>

<!ELEMENT settings (setting+)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting id CDATA #REQUIRED>
<!ATTLIST setting type (text|number|email|boolean|password|url|select|textarea|timestamp|foreign_key|tags) #REQUIRED>
<!ATTLIST setting category CDATA #IMPLIED>
<!ATTLIST setting default CDATA #IMPLIED>
<!ATTLIST setting selection CDATA #IMPLIED>

<!ELEMENT pages (page+)>

<!ELEMENT page (page*, script*, css*)>
<!ATTLIST page id CDATA #REQUIRED>
<!ATTLIST page template CDATA #REQUIRED>
<!ATTLIST page role CDATA #REQUIRED>
<!ATTLIST page model CDATA #IMPLIED>
<!ATTLIST page parentItem CDATA #IMPLIED>
<!ATTLIST page navweight CDATA #IMPLIED>
<!ATTLIST page navitem (true|false) "false">
<!ATTLIST page navitemOnlyForConfigEnabled CDATA #IMPLIED>
<!ATTLIST page premiumBalanceMin CDATA #IMPLIED>

<!ELEMENT script EMPTY>
<!ATTLIST script file CDATA #REQUIRED>
<!ATTLIST script debugonly (true|false) "false">
<!ATTLIST script productiononly (true|false) "false">

<!ELEMENT css EMPTY>
<!ATTLIST css file CDATA #REQUIRED>
<!ATTLIST css debugonly (true|false) "false">
<!ATTLIST css productiononly (true|false) "false">

<!ELEMENT blocks (block+)>

<!ELEMENT block EMPTY>
<!ATTLIST block id CDATA #REQUIRED>
<!ATTLIST block template CDATA #REQUIRED>
<!ATTLIST block role CDATA #REQUIRED>
<!ATTLIST block model CDATA #IMPLIED>
<!ATTLIST block includepages CDATA #IMPLIED>
<!ATTLIST block area (sidebar|content_top|content_bottom|custom) #IMPLIED>
<!ATTLIST block weight CDATA #IMPLIED>
<!ATTLIST block excludepages CDATA #IMPLIED>
<!ATTLIST block premiumBalanceMin CDATA #IMPLIED>

<!ELEMENT actions (action+)>

<!ELEMENT action (param*)>
<!ATTLIST action id CDATA #REQUIRED>
<!ATTLIST action role CDATA #REQUIRED>
<!ATTLIST action controller CDATA #REQUIRED>
<!ATTLIST action premiumBalanceMin CDATA #IMPLIED>
<!ATTLIST action log (true|false) "false">

<!ELEMENT param EMPTY>
<!ATTLIST param id CDATA #REQUIRED>
<!ATTLIST param type (text|number|email|boolean|password|date|url|percent) #REQUIRED>
<!ATTLIST param required (true|false) "false">
<!ATTLIST param min CDATA #IMPLIED>
<!ATTLIST param max CDATA #IMPLIED>
<!ATTLIST param validator CDATA #IMPLIED>

<!ELEMENT plugins (eventlistener+)>

<!ELEMENT eventlistener EMPTY>
<!ATTLIST eventlistener event CDATA #REQUIRED>
<!ATTLIST eventlistener class CDATA #REQUIRED>
<!ATTLIST eventlistener method CDATA #REQUIRED>

=== astroChasqui/websoccer_es/modules/transferoffers/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

    <dependencies>
        <dependency module="transfermarket" version="1.0.0"/>
    </dependencies>
    
    <admin>
        <adminpage
            id="transfer_offer"
            entity="transfer_offer"
            navcategory="league"
            permissionrole="r_daten" >

            <entity dbtable="transfer_offer AS OfferTab" >

                <overview add="false" delete="true" edit="false" >

                    <column
                        id="entity_transfer_offer_submitted_date"
                        field="OfferTab.submitted_date"
                        type="timestamp"
                        sort="true" />
                    
                    <column
                        id="entity_transfer_offer_player_id"
                        field="CONCAT(PlayerTab.vorname, ' ', IF(PlayerTab.kunstname IS NOT NULL, CONCAT('\'', PlayerTab.kunstname, '\' '), ''), PlayerTab.nachname)"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_transfer_offer_receiver_club_id"
                        field="ClubTab.name"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_transfer_offer_sender_club_id"
                        field="SenderClubTab.name"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_transfer_offer_offer_amount"
                        field="OfferTab.offer_amount"
                        type="number"
                        sort="true" />
                    
                    <column
                        id="entity_transfer_offer_offer_player1"
                        field="CONCAT(ExPlayer1Tab.vorname, ' ', ExPlayer1Tab.nachname)"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_transfer_offer_offer_player2"
                        field="CONCAT(ExPlayer2Tab.vorname, ' ', ExPlayer2Tab.nachname)"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_transfer_offer_rejected_date"
                        field="OfferTab.rejected_date"
                        type="timestamp"
                        sort="true" />
                    
                    <column
                        id="entity_transfer_offer_admin_approval_pending"
                        field="OfferTab.admin_approval_pending"
                        type="boolean"
                        sort="true" 
                        filter="true"
                        converter="TransferOfferApprovalLinkConverter" />

                    <join type="INNER" jointable="spieler AS PlayerTab" joincondition="OfferTab.player_id = PlayerTab.id" />
                	<join type="INNER" jointable="verein AS ClubTab" joincondition="OfferTab.receiver_club_id = ClubTab.id" />
                	<join type="INNER" jointable="verein AS SenderClubTab" 
                	    joincondition="OfferTab.sender_club_id = SenderClubTab.id" />
                	<join type="LEFT" jointable="spieler AS ExPlayer1Tab" joincondition="OfferTab.offer_player1 = ExPlayer1Tab.id" />
                	<join type="LEFT" jointable="spieler AS ExPlayer2Tab" joincondition="OfferTab.offer_player2 = ExPlayer2Tab.id" />
                </overview>

                <editform>
                    <field id="submitted_date" type="timestamp" required="true" />
                    <field id="player_id" type="foreign_key" entity="player" 
					    jointable="spieler" labelcolumns="nachname, vorname" required="true" />
					<field id="receiver_club_id" type="foreign_key" entity="club" 
					    jointable="verein" labelcolumns="name" required="true" />
					<field id="sender_club_id" type="foreign_key" entity="club" 
					    jointable="verein" labelcolumns="name" required="true" />
					<field id="sender_user_id" type="foreign_key" entity="users" 
					    jointable="user" labelcolumns="nick" required="true" />
					
					<field id="offer_amount" type="number" required="true" />
					<field id="offer_message" type="textarea" required="false" />
					
					<field id="offer_player1" type="foreign_key" entity="player" 
					    jointable="spieler" labelcolumns="nachname, vorname" required="false" />
					
					<field id="offer_player2" type="foreign_key" entity="player" 
					    jointable="spieler" labelcolumns="nachname, vorname" required="false" />
					
                </editform>
            </entity>
        </adminpage>
        
    </admin>
    
	<settings>
	    <setting id="transferoffers_enabled" category="transfermarket" type="boolean" default="1" />
	    <setting id="transferoffers_transfer_stop_days" category="transfermarket" type="number" default="30" />
	    <setting id="transferoffers_adminapproval_required" category="transfermarket" type="boolean" default="0" />
	    <setting id="transferoffers_contract_matches" category="transfermarket" type="number" default="20" />
	</settings>
	
    <pages>
        <page
            id="transferoffers"
            template="transferoffers"
            model="TransferOffersModel"
            role="user"
            navitem="true"
            navweight="2"
            parentItem="office" 
            navitemOnlyForConfigEnabled="transferoffers_enabled" />
    </pages> 
  
    <blocks>
        
        <block
            id="directtransfer-sentoffers"
            template="directtransfer-sentoffers"
            model="TransferOffersSentModel"
            includepages="none"
            area="custom"
            role="user" />

        <block
            id="directtransfer-offer"
            template="directtransfer-offer"
            model="DirectTransferOfferModel"
            includepages="player"
            area="content_top"
            weight="0"
            role="user" />
        
        <block
            id="directtransfer-offer-form"
            template="directtransfer-offer-form"
            model="DirectTransferOfferModel"
            includepages="none"
            area="custom"
            role="user" />
        
    </blocks>
    
	<actions>
		<action id="directtransfer-offer" controller="DirectTransferOfferController" role="user" log="true">
			<param id="id" type="number" required="true" />
			<param id="amount" type="number" required="true" min="1" max="1000000000" />
			<param id="exchangeplayer1" type="number" />
			<param id="exchangeplayer2" type="number" />
			<param id="comment" type="text" max="255" />
		</action>
		
		<action id="directtransfer-accept" controller="DirectTransferAcceptController" role="user">
			<param id="id" type="number" required="true" />
		</action>
		
		<action id="directtransfer-cancel" controller="DirectTransferCancelController" role="user">
			<param id="id" type="number" required="true" />
		</action>
		
		<action id="directtransfer-reject" controller="DirectTransferRejectController" role="user">
			<param id="id" type="number" required="true" />
			<param id="comment" type="text" max="255" />
			<param id="allow_alternative" type="boolean" />
		</action>
		
	</actions>
  
</module>

=== astroChasqui/websoccer_es/modules/profile/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

    <dependencies>
        <dependency module="formauthentication" version="1.0.0" />
    </dependencies>
    
    <pages>
        <page
            id="profile"
            template="profile"
            model="ProfileModel"
            role="user">
            <page
	            id="enter-username"
	            template="enter_username"
	            role="user" />
            
            <page
	            id="change-profile-picture"
	            template="change_profile_picture"
	            role="user" />
        </page>

    </pages> 
    
    <blocks>

        <block
            id="userprofile"
            template="userprofile"
            model="ProfileBlockModel"
            includepages="all"
            area="sidebar"
            weight="0"
            role="user" />
        
        <block
            id="user-clubs-selection"
            template="user_clubs_selection"
            model="UserClubsSelectionModel"
            includepages="none"
            area="custom"
            weight="0"
            role="user" />
        
    </blocks>
    
  <actions>
	<action id="save-profile" controller="SaveProfileController" role="user">
		<param id="newemail" type="text" required="false" validator="EmailValidator"/>
		<param id="newpassword" type="text" required="false" min="6" max="32" validator="PasswordValidator" />
		
		<param id="realname" type="text" required="false" max="80" />
		<param id="place" type="text" required="false" max="50" />
		<param id="country" type="text" required="false" max="40" />
		<param id="birthday" type="date" required="false" max="20" />
		<param id="occupation" type="text" required="false" max="50" />
		<param id="interests" type="text" required="false" max="250" />
		<param id="favorite_club" type="text" required="false" max="100" />
		<param id="homepage" type="url" required="false" max="250" />
		<param id="c_hideinonlinelist" type="boolean" required="false" />
	</action>
	
	<action id="save-username" controller="SaveUsernameController" role="user">
		<param id="nick" type="text" required="true" min="3" max="24" />
		<param id="termsandconditions" type="boolean" required="true" />
	</action>
	
	<action id="upload-profile-picture" controller="UploadProfilePictureController" role="user">
	</action>
	
	<action id="delete-profile-picture" controller="DeleteProfilePictureController" role="user">
	</action>
	
	<action id="select-team" controller="SelectTeamController" role="user">
		<param id="id" type="number" required="true" min="1" max="2000000000" />
	</action>
	
  </actions>
    
</module>

=== astroChasqui/websoccer_es/modules/freeclubs/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

    <dependencies>
        <dependency module="clubs" version="1.0.0"/>
    </dependencies>
    
  <settings>
      <setting id="assign_team_automatically" category="game" type="boolean" default="1" />
      <setting id="max_number_teams_per_user" category="game" type="number" default="1" />
      <setting id="additional_team_min_highscore" category="game" type="number" default="100" />
  </settings>
  
    <pages>
        <page
            id="freeclubs"
            template="freeclubs"
            model="FreeClubsModel"
            role="user,guest"
            navitem="true"
            navweight="4"/>

    </pages> 
    
  <actions>
	<action id="choose-team" controller="ChooseTeamController" role="user">
		<param id="teamId" type="number" required="true" />
	</action>
	
	<action id="choose-additional-team" controller="ChooseAdditionalTeamController" role="user">
		<param id="teamId" type="number" required="true" />
	</action>
  </actions>
    
</module>

=== astroChasqui/websoccer_es/modules/premium/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
  
  	<settings>
      	<setting id="premium_enabled" category="premium" type="boolean" default="false" />
      	<setting id="premium_credit_unit" category="premium" type="text" default="Coins" />
      	<setting id="premium_infopage" category="premium" type="text" default="premium-feature-requested" />
      	
      	<setting id="premium_price_options" category="premium" type="tags" default="5:10,20:50,50:150" />
      	<setting id="premium_currency" category="premium" type="text" default="EUR" />
      	<setting id="premium_initial_credit" category="premium" type="number" default="0" />
      	
      	<setting id="premium_exchangerate_gamecurrency" category="premium" type="number" default="1000000" />
  	</settings>
  	
  	<admin>
        <adminpage
            id="premiumstatement"
            entity="premiumstatement"
            navcategory="website"
            permissionrole="r_user" >

            <entity dbtable="premiumstatement AS TransactionTab" >

                <overview delete="true" edit="false" >

                    <column
                        id="entity_premiumstatement_user_id"
                        field="UserTab.nick"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_premiumstatement_action_id"
                        field="TransactionTab.action_id"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_premiumstatement_amount"
                        field="TransactionTab.amount"
                        type="number"
                        sort="true" />

                    <column
                        id="entity_premiumstatement_created_date"
                        field="TransactionTab.created_date"
                        type="timestamp"
                        sort="true" />
                    
                	<join type="LEFT" jointable="user AS UserTab" joincondition="TransactionTab.user_id = UserTab.id" />
                </overview>

                <editform>
					<field id="user_id" type="foreign_key" entity="users" 
					    jointable="user" cascade="delete" labelcolumns="nick" required="true" />
					<field id="created_date" type="timestamp" required="true"  />
					<field id="action_id" type="text" required="true"  />
					<field id="subject_data" type="textarea" required="false"  />
					<field id="amount" type="number" required="true" converter="PremiumTransactionConverter" />
					
                </editform>
            </entity>
        </adminpage>
        
        <adminpage
            id="premiumpayment"
            entity="premiumpayment"
            navcategory="website"
            permissionrole="r_user" >

            <entity dbtable="premiumpayment AS TransactionTab" >

                <overview delete="true" edit="false" >

                    <column
                        id="entity_premiumpayment_user_id"
                        field="UserTab.nick"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_premiumpayment_amount"
                        field="(TransactionTab.amount / 100)"
                        type="number"
                        sort="true" />

                    <column
                        id="entity_premiumpayment_created_date"
                        field="TransactionTab.created_date"
                        type="timestamp"
                        sort="true" />
                    
                	<join type="LEFT" jointable="user AS UserTab" joincondition="TransactionTab.user_id = UserTab.id" />
                </overview>
                
                <editform>
					<field id="user_id" type="foreign_key" entity="users" 
					    jointable="user" cascade="delete" labelcolumns="nick" required="true" />
					<field id="created_date" type="timestamp" required="true"  />
					<field id="amount" type="number" required="true" />
					
                </editform>

            </entity>
        </adminpage>
    </admin>
  	
  	<pages>
	    <page id="premiumaccount"
	        role="user"
	        template="premiumaccount"
	        model="PremiumAccountModel"
	        parentItem="profile">
            <page id="premium-feature-requested"
	        	role="user"
	        	template="premium_feature_requested"/>
            
            <page id="premium-confirm-action"
	        	role="user"
	        	template="premium_confirm_action"/>
            
            <page id="premium-exchange"
	        	role="user"
	        	template="premium_exchange">
               <page id="premium-exchange-confirm"
	        		role="user"
	        		template="premium_exchange_confirm" /> 
            </page>
	    </page>
	</pages>
	
  	<actions>
  	    <action id="exchange-premium" controller="ExchangePremiumController" role="user">
  	        <param id="validateonly" type="boolean" />
  	        <param id="amount" type="number" min="1" required="true" />
  	    </action>
  	    
  	</actions>
  
</module>

=== astroChasqui/websoccer_es/modules/season/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

    <dependencies>
        <dependency module="leagues" version="1.0.0"/>
    </dependencies>
    
    <admin>
        <adminpage id="schedulegenerator" permissionrole="r_spiele" navcategory="season" filename="schedulegenerator"/>
        
        <adminpage
            id="season"
            entity="season"
            navcategory="season"
            permissionrole="r_spiele" >

            <entity dbtable="saison AS SeasonTab" >

                <overview delete="true" edit="true" >

                    <column
                        id="entity_season_name"
                        field="SeasonTab.name"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_season_liga_id"
                        field="LeagueTab.name"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_season_beendet"
                        field="SeasonTab.beendet"
                        type="boolean"
                        filter="true" />
                    
                    
                	<join type="LEFT" jointable="liga AS LeagueTab" joincondition="LeagueTab.id = SeasonTab.liga_id" />
                </overview>

                <editform>
                    
                    <field id="name" type="text" required="true" />
                    <field id="liga_id" type="foreign_key" entity="league" jointable="liga" cascade="delete" labelcolumns="land, name" required="true" />
                    <field id="beendet" type="boolean" />
                    
                    <field id="platz_1_id" type="foreign_key" entity="club" jointable="verein" labelcolumns="name" />
                    <field id="platz_2_id" type="foreign_key" entity="club" jointable="verein" labelcolumns="name" />
                    <field id="platz_3_id" type="foreign_key" entity="club" jointable="verein" labelcolumns="name" />
                    <field id="platz_4_id" type="foreign_key" entity="club" jointable="verein" labelcolumns="name" />
                    <field id="platz_5_id" type="foreign_key" entity="club" jointable="verein" labelcolumns="name" />
					
                </editform>
            </entity>
        </adminpage>
        
        <adminpage
            id="complete-season"
            filename="season-complete"
            navcategory="season"
            permissionrole="r_spiele" />
    </admin>
    
    <blocks>

        <block
            id="season-picker"
            template="season-picker"
            model="SeasonsOfLeagueModel"
            includepages="none"
            area="custom"
            weight="0"
            role="user,guest" />
        
        <block
            id="results-list"
            template="results-list"
            model="MatchDayResultsModel"
            includepages="none"
            area="custom"
            weight="0"
            role="user,guest" />
        
        <block
            id="latest-results"
            template="results-list"
            model="LatestResultsModel"
            includepages="none"
            area="custom"
            weight="0"
            role="user,guest" />
        
    </blocks>
    
</module>

=== astroChasqui/websoccer_es/modules/office/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

    <dependencies>
        <dependency module="users" version="1.0.0" />
    </dependencies>
    
    <settings>
      <setting id="contract_max_number_of_remaining_matches" category="game" type="number" default="15" />
  	</settings>
    
    <pages>
        <page
            id="office"
            template="office-overview"
            model="OfficeModel"
            navitem="true"
            navweight="2"
            role="user">
            
	        <page
	            id="myteam"
	            template="myteam-overview"
	            model="MyTeamModel"
	            navitem="true"
	            navweight="2"
	            role="user">
		        <page
		            id="extend-contract"
		            model="PlayerDetailsModel"
		            template="extend-contract"
		            role="user" />
	  		</page>
	  		
	        <page
	            id="finances"
	            template="finances"
	            model="FinancesModel"
	            navitem="true"
	            navweight="4"
	            role="user"/>
	        
	        <page
	            id="tickets"
	            template="tickets"
	            model="TicketsModel"
	            navitem="true"
	            navweight="5"
	            role="user"/>
            
         </page>

    </pages> 
    
    <blocks>

        <block
            id="extend-contract-form"
            template="extend-contract-form"
            model="PlayerDetailsModel"
            includepages="extend-contract"
            area="content_bottom"
            weight="0"
            role="user" />
        
       <block
            id="finances-summary"
            template="finances_summary"
            model="FinancesSummaryModel"
            includepages="finances"
            area="content_top"
            weight="0"
            role="user" />
        
    </blocks>
    
  <actions>
	<action id="extend-contract" controller="ExtendContractController" role="user" log="true">
		<param id="salary" type="number" required="true" max="1000000000" />
		<param id="goal_bonus" type="number" required="false"/>
		<param id="matches" type="number" required="true" min="20" max="100"/>
		<param id="id" type="number" required="true" />
	</action>
	
	<action id="save-tickets" controller="SaveTicketsController" role="user" log="true">
		<param id="p_stands" type="number" required="true" min="1" max="1000" />
		<param id="p_seats" type="number" required="true" min="1" max="1000" />
		<param id="p_stands_grand" type="number" required="true" min="1" max="1000" />
		<param id="p_seats_grand" type="number" required="true" min="1" max="1000" />
		<param id="p_vip" type="number" required="true" min="1" max="1000" />
	</action>
	
	<action id="markAsUnsellable" controller="MarkAsUnsellableController" role="user">
		<param id="id" type="number" required="true" min="1" max="1000000000" />
	</action>
	
	<action id="unmarkUnsellable" controller="UnmarkUnsellableController" role="user">
		<param id="id" type="number" required="true" min="1" max="1000000000" />
	</action>
	
	<action id="select-captain" controller="SelectCaptainController" role="user" log="true">
		<param id="id" type="number" required="true" min="1" max="1000000000" />
	</action>
	
  </actions>
    
</module>
