=== astroChasqui/websoccer_es/modules/module.dtd
<!ELEMENT module (admin?|settings?|pages?|dependencies?|blocks?|actions?|plugins?)*>
<!ATTLIST module version CDATA #REQUIRED>

<!ELEMENT dependencies (dependency+)>
<!ELEMENT dependency EMPTY>
<!ATTLIST dependency module CDATA #REQUIRED>
<!ATTLIST dependency version CDATA #REQUIRED>

<!ELEMENT admin (adminpage+)>

<!ELEMENT adminpage (entity?)>
<!ATTLIST adminpage id CDATA #REQUIRED>
<!ATTLIST adminpage navcategory CDATA #REQUIRED>
<!ATTLIST adminpage entity CDATA #IMPLIED>
<!ATTLIST adminpage permissionrole (r_admin|r_daten|r_adminuser|r_news|r_spiele|r_user) #IMPLIED>
<!ATTLIST adminpage filename CDATA #IMPLIED>

<!ELEMENT entity (overview, editform?)>
<!ATTLIST entity dbtable CDATA #REQUIRED>

<!ELEMENT overview (column+, join*)>
<!ATTLIST overview add (true|false) "true">
<!ATTLIST overview edit (true|false) "false">
<!ATTLIST overview delete (true|false) "false">
<!ATTLIST overview logging (true|false) "false">
<!ATTLIST overview loggingcolumns CDATA #IMPLIED>

<!ELEMENT column EMPTY>
<!ATTLIST column id CDATA #REQUIRED>
<!ATTLIST column filter (true|false) "false">
<!ATTLIST column sort (true|false) "false">
<!ATTLIST column type (text|number|email|boolean|select|timestamp|percent|fk) #REQUIRED>
<!ATTLIST column field CDATA #REQUIRED>
<!ATTLIST column selection CDATA #IMPLIED>
<!ATTLIST column converter CDATA #IMPLIED>
<!ATTLIST column hidden (true|false) "false">

<!ELEMENT join EMPTY>
<!ATTLIST join type (LEFT|INNER|RIGHT) #REQUIRED>
<!ATTLIST join jointable CDATA #REQUIRED>
<!ATTLIST join joincondition CDATA #REQUIRED>

<!ELEMENT editform (field+)>

<!ELEMENT field EMPTY>
<!ATTLIST field id CDATA #REQUIRED>
<!ATTLIST field required (true|false) "false">
<!ATTLIST field editonly (true|false) "false">
<!ATTLIST field type (text|number|email|boolean|password|url|select|textarea|file|timestamp|color|date|percent|foreign_key) #REQUIRED>
<!ATTLIST field converter CDATA #IMPLIED>
<!ATTLIST field validator CDATA #IMPLIED>
<!ATTLIST field entity CDATA #IMPLIED>
<!ATTLIST field jointable CDATA #IMPLIED>
<!ATTLIST field cascade CDATA #FIXED "delete">
<!ATTLIST field labelcolumns CDATA #IMPLIED>
<!ATTLIST field selection CDATA #IMPLIED>
<!ATTLIST field roles CDATA #IMPLIED>
<!ATTLIST field readonly (true|false) "false">
<!ATTLIST field default CDATA #IMPLIED>

<!ELEMENT settings (setting+)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting id CDATA #REQUIRED>
<!ATTLIST setting type (text|number|email|boolean|password|url|select|textarea|timestamp|foreign_key|tags) #REQUIRED>
<!ATTLIST setting category CDATA #IMPLIED>
<!ATTLIST setting default CDATA #IMPLIED>
<!ATTLIST setting selection CDATA #IMPLIED>

<!ELEMENT pages (page+)>

<!ELEMENT page (page*, script*, css*)>
<!ATTLIST page id CDATA #REQUIRED>
<!ATTLIST page template CDATA #REQUIRED>
<!ATTLIST page role CDATA #REQUIRED>
<!ATTLIST page model CDATA #IMPLIED>
<!ATTLIST page parentItem CDATA #IMPLIED>
<!ATTLIST page navweight CDATA #IMPLIED>
<!ATTLIST page navitem (true|false) "false">
<!ATTLIST page navitemOnlyForConfigEnabled CDATA #IMPLIED>
<!ATTLIST page premiumBalanceMin CDATA #IMPLIED>

<!ELEMENT script EMPTY>
<!ATTLIST script file CDATA #REQUIRED>
<!ATTLIST script debugonly (true|false) "false">
<!ATTLIST script productiononly (true|false) "false">

<!ELEMENT css EMPTY>
<!ATTLIST css file CDATA #REQUIRED>
<!ATTLIST css debugonly (true|false) "false">
<!ATTLIST css productiononly (true|false) "false">

<!ELEMENT blocks (block+)>

<!ELEMENT block EMPTY>
<!ATTLIST block id CDATA #REQUIRED>
<!ATTLIST block template CDATA #REQUIRED>
<!ATTLIST block role CDATA #REQUIRED>
<!ATTLIST block model CDATA #IMPLIED>
<!ATTLIST block includepages CDATA #IMPLIED>
<!ATTLIST block area (sidebar|content_top|content_bottom|custom) #IMPLIED>
<!ATTLIST block weight CDATA #IMPLIED>
<!ATTLIST block excludepages CDATA #IMPLIED>
<!ATTLIST block premiumBalanceMin CDATA #IMPLIED>

<!ELEMENT actions (action+)>

<!ELEMENT action (param*)>
<!ATTLIST action id CDATA #REQUIRED>
<!ATTLIST action role CDATA #REQUIRED>
<!ATTLIST action controller CDATA #REQUIRED>
<!ATTLIST action premiumBalanceMin CDATA #IMPLIED>
<!ATTLIST action log (true|false) "false">

<!ELEMENT param EMPTY>
<!ATTLIST param id CDATA #REQUIRED>
<!ATTLIST param type (text|number|email|boolean|password|date|url|percent) #REQUIRED>
<!ATTLIST param required (true|false) "false">
<!ATTLIST param min CDATA #IMPLIED>
<!ATTLIST param max CDATA #IMPLIED>
<!ATTLIST param validator CDATA #IMPLIED>

<!ELEMENT plugins (eventlistener+)>

<!ELEMENT eventlistener EMPTY>
<!ATTLIST eventlistener event CDATA #REQUIRED>
<!ATTLIST eventlistener class CDATA #REQUIRED>
<!ATTLIST eventlistener method CDATA #REQUIRED>

=== astroChasqui/websoccer_es/modules/userbadges/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
    
    <admin>
        <adminpage
            id="badge"
            entity="badge"
            navcategory="website"
            permissionrole="r_user" >

            <entity dbtable="badge AS BadgeTab" >

                <overview delete="true" edit="true" >

                    <column
                        id="entity_badge_name"
                        field="BadgeTab.name"
                        type="text"
                        sort="true" />
                    
                    <column
                        id="entity_badge_level"
                        field="BadgeTab.level"
                        type="text"
                        sort="true" />
                    
           			<column
                        id="entity_badge_event"
                        field="BadgeTab.event"
                        type="text"
                        sort="true" />
           			
           			<column
                        id="entity_badge_event_benchmark"
                        field="BadgeTab.event_benchmark"
                        type="number"
                        sort="true" />
                </overview>

                <editform>
                    <field id="name" type="text" required="true" />
                    <field id="description" type="text" required="false" />
					<field id="level" type="select" required="true" 
					    selection="bronze,silver,gold" />
					<field id="event" type="select" required="true" 
					    selection="membership_since_x_days,win_with_x_goals_difference,completed_season_at_x,x_trades,stadium_construction_by_x,cupwinner" />
					<field id="event_benchmark" type="number" required="true" default="0" />
                </editform>
            </entity>
        </adminpage>
    </admin>
    
    <pages>
        <page
            id="badges"
            template="badges"
            model="BadgesModel"
            role="user,guest"
            parentItem="user"  />
    </pages> 
</module>

=== astroChasqui/websoccer_es/modules/randomevents/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
    
    <settings>
      	<setting id="randomevents_interval_days" category="game" type="number" default="10" />
  	</settings>

    <admin>
        <adminpage
            id="randomevent"
            entity="randomevent"
            navcategory="league"
            permissionrole="r_daten" >

            <entity dbtable="randomevent AS EventTab" >

                <overview delete="true" edit="true" >

                    <column
                        id="entity_randomevent_message"
                        field="EventTab.message"
                        type="text"
                        sort="true" />
                    
                    <column
                        id="entity_randomevent_effect"
                        field="EventTab.effect"
                        type="text"
                        sort="true" />
                    
           			<column
                        id="entity_randomevent_weight"
                        field="EventTab.weight"
                        type="number"
                        sort="true" />
                </overview>

                <editform>
                    <field id="message" type="text" required="true" />
					<field id="effect" type="select" required="true" 
					    selection="money,player_injured,player_blocked,player_happiness,player_fitness,player_stamina" />
					
					<field id="effect_money_amount" type="number" />
					<field id="effect_blocked_matches" type="number" />
					<field id="effect_skillchange" type="number" />
					
					<field id="weight" type="number" required="true" default="3" />
                </editform>
            </entity>
        </adminpage>
    </admin>
    
</module>

=== astroChasqui/websoccer_es/modules/facebook/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

  <settings>
      <setting id="facebook_enable_login" category="social" type="boolean" default="0" />
      
      <setting id="facebook_appid" category="social" type="text" default="" />
      
      <setting id="facebook_appsecret" category="social" type="text" default="" />
      
      <setting id="facebook_enable_comments" category="social" type="boolean" default="0" />
      
      <setting id="facebook_enable_likebutton" category="social" type="boolean" default="0" />
  </settings>
  
  <blocks>

        <block
            id="facebook-login-sidebar"
            template="facebookloginbox"
            model="FacebookLoginModel"
            includepages="all"
            area="sidebar"
            weight="1"
            role="guest" />
        
        <block
            id="facebook-like"
            template="facebook_like"
            includepages="home,news-details,match,todaysmatches,highscore,freeclubs"
            area="content_bottom"
            weight="5"
            role="guest,user" />
        
        <block
            id="facebook-sdk"
            template="facebook_sdk"
            includepages="all"
            area="content_top"
            weight="0"
            role="guest,user" />
        
        <block
            id="facebook-comments"
            template="facebook_comments"
            includepages="news-details,match"
            area="content_bottom"
            weight="10"
            role="guest,user" />
        
  </blocks>
    
  <actions>
      
     <action id="facebook-login" controller="FacebookLoginController" role="guest,user">
		<param id="error" type="text" required="false"/>
	</action>
	
     <action id="facebook-logout" controller="FacebookLogoutController" role="user,guest" />
  </actions>

</module>

=== astroChasqui/websoccer_es/modules/transfermarket/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

    <dependencies>
        <dependency module="players" version="1.0.0"/>
    </dependencies>
    
  <settings>
      <setting id="transfermarket_enabled" category="transfermarket" type="boolean" default="1" />
      <setting id="transfermarket_duration_days" category="transfermarket" type="number" default="7" />
      <setting id="transfermarket_computed_marketvalue" category="transfermarket" type="boolean" default="1" />
      <setting id="transfermarket_value_per_strength" category="transfermarket" type="number" default="10000" />
      <setting id="transfermarket_min_teamsize" category="transfermarket" type="number" default="18" />
      <setting id="transfermarket_max_transactions_between_users" category="transfermarket" type="number" default="2" />
  </settings>
  
    <pages>
        <page
            id="transfermarket"
            template="transfermarket-overview"
            model="TransfermarketOverviewModel"
            role="user"
            navitem="true"
            navweight="2"
            parentItem="office"
            navitemOnlyForConfigEnabled="transfermarket_enabled">
	        <page
	            id="sell-player"
	            template="sell-player"
	            model="PlayerDetailsModel"
	            role="user" />
	        
	        <page
	            id="transfer-bid"
	            template="transfer-bid"
	            model="PlayerDetailsModel"
	            role="user">
	            <script file="jquery.countdown.min.js" />
	         </page>
        </page>

    </pages> 
    
    <blocks>

        <block
            id="transfer-bid"
            template="transfer-bid-block"
            model="TransferBidModel"
            includepages="transfer-bid"
            area="content_bottom"
            weight="0"
            role="user" />
        
        <block
            id="transfermarket-mybids"
            template="transfer-bids-list"
            model="MyTransferBidsModel"
            includepages="none"
            area="custom"
            role="user" />
        
        <block
            id="transfermarket-mytransfers"
            template="transfers-list"
            model="MyTransfersModel"
            includepages="none"
            area="custom"
            role="user" />
        
        <block
            id="transfermarket-lasttransfers"
            template="transfers-list"
            model="LastTransfersModel"
            includepages="none"
            area="custom"
            role="user" />
        
        <block
            id="teamtransfers"
            template="transfers-list"
            model="TeamTransfersModel"
            includepages="none"
            area="custom"
            role="user,guest" />
        
        <block
            id="usertransfers"
            template="transfers-list"
            model="UserTransfersModel"
            includepages="none"
            area="custom"
            role="user" />
        
    </blocks>
    
  <actions>
	<action id="sell-player" controller="SellPlayerController" role="user" log="true">
		<param id="min_bid" type="number" required="true" max="1000000000" />
		<param id="id" type="number" required="true" />
	</action>
	
	<action id="transfer-bid" controller="TransferBidController" role="user" log="true">
		<param id="amount" type="number" max="1000000000" min="1" />
		<param id="handmoney" type="number" max="1000000000" min="1" />
		<param id="contract_salary" type="number" max="1000000000" required="true" />
		<param id="contract_goal_bonus" type="number" max="1000000000" min="1"/>
		<param id="contract_matches" type="number" min="20" max="100" required="true" />
		<param id="id" type="number" required="true" />
	</action>
	
	<action id="remove-player-from-transfermarket" controller="RemovePlayerFromTransfermarketController" role="user">
		<param id="id" type="number" required="true" />
	</action>
  </actions>
    
</module>

=== astroChasqui/websoccer_es/modules/googleplus/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

  <settings>
      <setting id="googleplus_enable_login" category="social" type="boolean" default="0" />
      
      <setting id="googleplus_appname" category="social" type="text" default="" />
      <setting id="googleplus_clientid" category="social" type="text" default="" />
      <setting id="googleplus_clientsecret" category="social" type="text" default="" />
      <setting id="googleplus_developerkey" category="social" type="text" default="" />
      
      <setting id="googleplus_enable_likebutton" category="social" type="boolean" default="0" />
  </settings>
  
  <blocks>
      
       <block
            id="googleplus-login-sidebar"
            template="googleplusloginbox"
            model="GoogleplusLoginModel"
            includepages="all"
            area="sidebar"
            weight="1"
            role="guest" />
        

        <block
            id="googleplus-like"
            template="googleplus_like"
            includepages="home,news-details,match,todaysmatches,highscore,freeclubs"
            area="content_bottom"
            weight="5"
            role="guest,user" />
        
        
  </blocks>
  
  <actions>
      <action id="googleplus-login" controller="GoogleplusLoginController" role="guest" />
  </actions>
    
</module>

=== astroChasqui/websoccer_es/modules/clubs/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

    <dependencies>
        <dependency module="users" version="1.0.0"/>
        <dependency module="leagues" version="1.0.0"/>
    </dependencies>
    
    <admin>
        <adminpage
            id="club"
            entity="club"
            navcategory="league"
            permissionrole="r_daten" >

            <entity dbtable="verein AS ClubTab" >

                <overview delete="true" edit="true" logging="true" loggingcolumns="name,liga_id">

                    <column
                        id="entity_club_name"
                        field="ClubTab.name"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_club_liga_id"
                        field="LeagueTab.name"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_club_nationalteam"
                        field="ClubTab.nationalteam"
                        type="boolean"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_club_user_id"
                        field="UserTab.nick"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_club_finanz_budget"
                        field="ClubTab.finanz_budget"
                        type="number"
                        sort="true" />
                    
                    <column
                        id="entity_player"
                        field="(SELECT COUNT(*) FROM {tablePrefix}_spieler AS PlayerTab WHERE PlayerTab.verein_id = ClubTab.id)"
                        type="number"
                        sort="true" />
                    
                    <column
                        id="entity_club_status"
                        field="ClubTab.status"
                        type="boolean" />
                    
                	<join type="LEFT" jointable="liga AS LeagueTab" joincondition="ClubTab.liga_id = LeagueTab.id" />
		    		<join type="LEFT" jointable="user AS UserTab" joincondition="ClubTab.user_id = UserTab.id" />
                </overview>

                <editform>
                    <field id="name" type="text" required="true" />
					<field id="kurz" type="text" required="true" />
					<field id="nationalteam" type="boolean" required="false" />
					<field id="liga_id" type="foreign_key" entity="league" jointable="liga" cascade="delete" labelcolumns="land, name" required="false" default="0" />
					<field id="user_id" type="foreign_key" entity="users" jointable="user" labelcolumns="nick" />
					<field id="user_id_actual" type="foreign_key" entity="users" jointable="user" labelcolumns="nick" />
					<field id="interimmanager" type="boolean" required="false" />
					<field id="bild" type="file" />
					<field id="stadion_id" type="foreign_key" entity="stadium"  jointable="stadion" labelcolumns="name" />
					<field id="sponsor_id" type="foreign_key" entity="sponsor"  jointable="sponsor" labelcolumns="name" />
					<field id="sponsor_spiele" type="number" />
					<field id="finanz_budget" type="number" />
					<field id="min_target_rank" type="number" default="0" />
					<field id="preis_stehen" type="number" />
					<field id="preis_sitz" type="number" />
					<field id="preis_haupt_stehen" type="number" />
					<field id="preis_haupt_sitze" type="number" />
					<field id="preis_vip" type="number" />
					<field id="last_steh" type="number" editonly="true" />
					<field id="last_sitz" type="number" editonly="true" />
					<field id="last_haupt_steh" type="number" editonly="true" />
					<field id="last_haupt_sitz" type="number" editonly="true" />
					<field id="last_vip" type="number" editonly="true" />
					<field id="meisterschaften" type="number" editonly="true" />
					<field id="st_tore" type="number" editonly="true" />
					<field id="st_gegentore" type="number" editonly="true" />
					<field id="st_spiele" type="number" editonly="true" />
					<field id="st_siege" type="number" editonly="true" />
					<field id="st_niederlagen" type="number" editonly="true" />
					<field id="st_unentschieden" type="number" editonly="true" />
					<field id="st_punkte" type="number" editonly="true" />
					<field id="sa_tore" type="number" editonly="true" />
					<field id="sa_gegentore" type="number" editonly="true" />
					<field id="sa_spiele" type="number" editonly="true" />
					<field id="sa_siege" type="number" editonly="true" />
					<field id="sa_niederlagen" type="number" editonly="true" />
					<field id="sa_unentschieden" type="number" editonly="true" />
					<field id="sa_punkte" type="number" editonly="true" />
					<field id="captain_id" type="foreign_key" entity="player" jointable="spieler" labelcolumns="vorname,nachname,kunstname" required="false" default="0" />
					<field id="history" type="textarea" />
					<field id="status" type="boolean" default="1" />
                </editform>
            </entity>
        </adminpage>
    </admin>
    
    <pages>
        <page
            id="team"
            template="team-details"
            model="TeamDetailsModel"
            role="user,guest"
            parentItem="leagues" />

    </pages> 
    
    <blocks>

        <block
            id="teamplayers"
            template="teamplayers"
            model="TeamPlayersModel"
            includepages="team"
            area="custom"
            weight="0"
            role="user,guest" />
        

        <block
            id="team-results"
            template="results-list"
            model="TeamResultsModel"
            includepages="none"
            area="custom"
            weight="0"
            role="user,guest" />
        
        <block
            id="team-history"
            template="team_history"
            model="TeamHistoryModel"
            includepages="none"
            area="custom"
            weight="0"
            role="user" />
    </blocks>
</module>

=== astroChasqui/websoccer_es/modules/moneytransactions/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
    
    <settings>
      <setting id="no_transactions_for_teams_without_user" category="game" type="boolean" default="0" />
  	</settings>
    
    <admin>
        <adminpage
            id="transaction"
            entity="transaction"
            navcategory="league"
            permissionrole="r_daten" >

            <entity dbtable="konto AS TransactionTab" >

                <overview delete="true" edit="false" >

                    <column
                        id="entity_transaction_verein_id"
                        field="ClubTab.name"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_transaction_absender"
                        field="TransactionTab.absender"
                        converter="PaymentSenderMessageConverter"
                        type="text" />
                    
                    <column
                        id="entity_transaction_betrag"
                        field="TransactionTab.betrag"
                        type="number"
                        sort="true" />

                    <column
                        id="entity_transaction_datum"
                        field="TransactionTab.datum"
                        type="timestamp"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_transaction_verwendung"
                        field="TransactionTab.verwendung"
                        type="text"
                        converter="PaymentSubjectMessageConverter" />
                    
                	<join type="LEFT" jointable="verein AS ClubTab" joincondition="TransactionTab.verein_id = ClubTab.id" />
                </overview>

                <editform>
					<field id="verein_id" type="foreign_key" entity="club" 
					    jointable="verein" cascade="delete" labelcolumns="name" required="true" />
					<field id="datum" type="timestamp" required="true"  />
					<field id="absender" type="text" required="true"  />
					<field id="verwendung" type="text" required="true"  />
					<field id="betrag" type="number" required="true" converter="MoneyTransactionConverter" />
					
                </editform>
            </entity>
        </adminpage>
    </admin>
  
</module>
