=== astroChasqui/websoccer_es/modules/module.dtd
<!ELEMENT module (admin?|settings?|pages?|dependencies?|blocks?|actions?|plugins?)*>
<!ATTLIST module version CDATA #REQUIRED>

<!ELEMENT dependencies (dependency+)>
<!ELEMENT dependency EMPTY>
<!ATTLIST dependency module CDATA #REQUIRED>
<!ATTLIST dependency version CDATA #REQUIRED>

<!ELEMENT admin (adminpage+)>

<!ELEMENT adminpage (entity?)>
<!ATTLIST adminpage id CDATA #REQUIRED>
<!ATTLIST adminpage navcategory CDATA #REQUIRED>
<!ATTLIST adminpage entity CDATA #IMPLIED>
<!ATTLIST adminpage permissionrole (r_admin|r_daten|r_adminuser|r_news|r_spiele|r_user) #IMPLIED>
<!ATTLIST adminpage filename CDATA #IMPLIED>

<!ELEMENT entity (overview, editform?)>
<!ATTLIST entity dbtable CDATA #REQUIRED>

<!ELEMENT overview (column+, join*)>
<!ATTLIST overview add (true|false) "true">
<!ATTLIST overview edit (true|false) "false">
<!ATTLIST overview delete (true|false) "false">
<!ATTLIST overview logging (true|false) "false">
<!ATTLIST overview loggingcolumns CDATA #IMPLIED>

<!ELEMENT column EMPTY>
<!ATTLIST column id CDATA #REQUIRED>
<!ATTLIST column filter (true|false) "false">
<!ATTLIST column sort (true|false) "false">
<!ATTLIST column type (text|number|email|boolean|select|timestamp|percent|fk) #REQUIRED>
<!ATTLIST column field CDATA #REQUIRED>
<!ATTLIST column selection CDATA #IMPLIED>
<!ATTLIST column converter CDATA #IMPLIED>
<!ATTLIST column hidden (true|false) "false">

<!ELEMENT join EMPTY>
<!ATTLIST join type (LEFT|INNER|RIGHT) #REQUIRED>
<!ATTLIST join jointable CDATA #REQUIRED>
<!ATTLIST join joincondition CDATA #REQUIRED>

<!ELEMENT editform (field+)>

<!ELEMENT field EMPTY>
<!ATTLIST field id CDATA #REQUIRED>
<!ATTLIST field required (true|false) "false">
<!ATTLIST field editonly (true|false) "false">
<!ATTLIST field type (text|number|email|boolean|password|url|select|textarea|file|timestamp|color|date|percent|foreign_key) #REQUIRED>
<!ATTLIST field converter CDATA #IMPLIED>
<!ATTLIST field validator CDATA #IMPLIED>
<!ATTLIST field entity CDATA #IMPLIED>
<!ATTLIST field jointable CDATA #IMPLIED>
<!ATTLIST field cascade CDATA #FIXED "delete">
<!ATTLIST field labelcolumns CDATA #IMPLIED>
<!ATTLIST field selection CDATA #IMPLIED>
<!ATTLIST field roles CDATA #IMPLIED>
<!ATTLIST field readonly (true|false) "false">
<!ATTLIST field default CDATA #IMPLIED>

<!ELEMENT settings (setting+)>
<!ELEMENT setting EMPTY>
<!ATTLIST setting id CDATA #REQUIRED>
<!ATTLIST setting type (text|number|email|boolean|password|url|select|textarea|timestamp|foreign_key|tags) #REQUIRED>
<!ATTLIST setting category CDATA #IMPLIED>
<!ATTLIST setting default CDATA #IMPLIED>
<!ATTLIST setting selection CDATA #IMPLIED>

<!ELEMENT pages (page+)>

<!ELEMENT page (page*, script*, css*)>
<!ATTLIST page id CDATA #REQUIRED>
<!ATTLIST page template CDATA #REQUIRED>
<!ATTLIST page role CDATA #REQUIRED>
<!ATTLIST page model CDATA #IMPLIED>
<!ATTLIST page parentItem CDATA #IMPLIED>
<!ATTLIST page navweight CDATA #IMPLIED>
<!ATTLIST page navitem (true|false) "false">
<!ATTLIST page navitemOnlyForConfigEnabled CDATA #IMPLIED>
<!ATTLIST page premiumBalanceMin CDATA #IMPLIED>

<!ELEMENT script EMPTY>
<!ATTLIST script file CDATA #REQUIRED>
<!ATTLIST script debugonly (true|false) "false">
<!ATTLIST script productiononly (true|false) "false">

<!ELEMENT css EMPTY>
<!ATTLIST css file CDATA #REQUIRED>
<!ATTLIST css debugonly (true|false) "false">
<!ATTLIST css productiononly (true|false) "false">

<!ELEMENT blocks (block+)>

<!ELEMENT block EMPTY>
<!ATTLIST block id CDATA #REQUIRED>
<!ATTLIST block template CDATA #REQUIRED>
<!ATTLIST block role CDATA #REQUIRED>
<!ATTLIST block model CDATA #IMPLIED>
<!ATTLIST block includepages CDATA #IMPLIED>
<!ATTLIST block area (sidebar|content_top|content_bottom|custom) #IMPLIED>
<!ATTLIST block weight CDATA #IMPLIED>
<!ATTLIST block excludepages CDATA #IMPLIED>
<!ATTLIST block premiumBalanceMin CDATA #IMPLIED>

<!ELEMENT actions (action+)>

<!ELEMENT action (param*)>
<!ATTLIST action id CDATA #REQUIRED>
<!ATTLIST action role CDATA #REQUIRED>
<!ATTLIST action controller CDATA #REQUIRED>
<!ATTLIST action premiumBalanceMin CDATA #IMPLIED>
<!ATTLIST action log (true|false) "false">

<!ELEMENT param EMPTY>
<!ATTLIST param id CDATA #REQUIRED>
<!ATTLIST param type (text|number|email|boolean|password|date|url|percent) #REQUIRED>
<!ATTLIST param required (true|false) "false">
<!ATTLIST param min CDATA #IMPLIED>
<!ATTLIST param max CDATA #IMPLIED>
<!ATTLIST param validator CDATA #IMPLIED>

<!ELEMENT plugins (eventlistener+)>

<!ELEMENT eventlistener EMPTY>
<!ATTLIST eventlistener event CDATA #REQUIRED>
<!ATTLIST eventlistener class CDATA #REQUIRED>
<!ATTLIST eventlistener method CDATA #REQUIRED>

=== astroChasqui/websoccer_es/modules/news/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
  
  <admin>
	<adminpage id="news" permissionrole="r_news" navcategory="website" entity="news">
		<entity dbtable="news AS NewsTab">
		    <overview edit="true" delete="true">
		    	<column id="entity_news_titel" type="text" field="NewsTab.titel" filter="true" sort="true" />
		    	<column id="entity_news_datum" type="timestamp" field="NewsTab.datum" sort="true"/>    
		    	<column id="entity_admin_name" type="text" field="AdminTab.name" filter="true" sort="true" />   
		    	<column id="entity_news_status" type="boolean" field="NewsTab.status" />   
		    	<join type="LEFT" jointable="admin AS AdminTab" joincondition="AdminTab.id = NewsTab.autor_id" />
		    </overview>
		    <editform>
		        <field id="autor_id" type="foreign_key" jointable="admin" labelcolumns="name" required="true"/>
				<field id="titel" type="text" required="true" />
				<field id="datum" type="timestamp" required="true"/>
				<field id="nachricht" type="textarea" required="true" />
				<field id="linktext1" type="text" />
				<field id="linkurl1" type="url" />
				<field id="linktext2" type="text" />
				<field id="linkurl2" type="url" />
				<field id="linktext3" type="text" />
				<field id="linkurl3" type="url" />
				<field id="c_br" type="boolean" />
				<field id="c_links" type="boolean" />
				<field id="status" type="boolean" />        
		    </editform>
		    
		</entity>    
	</adminpage>
  </admin>
  
    <pages>
        <page
            id="news"
            model="NewsListModel"
            navitem="true"
            navweight="1"
            template="news-overview"
            role="guest,user">
	        <page
	            id="news-details"
	            model="NewsDetailsModel"
	            navitem="false"
	            template="news-details"
	            role="guest,user" />
        </page>
    </pages>
    
    <blocks>

        <block
            id="news"
            template="topnews"
            model="TopNewsListModel"
            includepages="home"
            area="custom"
            weight="0"
            role="guest,user" />
        
    </blocks>
</module>

=== astroChasqui/websoccer_es/modules/formauthentication/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

    <dependencies>
        <dependency module="userauthentication" version="1.0.0" />
        <dependency module="userregistration" version="1.0.0" />
    </dependencies>
    
    <pages>
        <page
            id="login"
            template="login"
            role="guest">
            <page
	            id="forgot-password"
	            template="forgot-password"
	            model="ForgotPasswordModel"
	            role="guest"/>
        </page>
        
        <page
            id="activate-user"
            template="activate-user"
            role="guest" />

    </pages>    
    
    <blocks>

        <block
            id="login-form"
            template="userlogin"
            includepages="all"
            excludepages="login,register"
            area="sidebar"
            weight="0"
            role="guest" />
        
    </blocks>
    
  <settings>
      <setting id="login_type" category="users" type="select" selection="email,username" default="email" />
      <setting id="login_method" category="users" type="text" default="DefaultUserLoginMethod" />
      <setting id="login_allow_sendingpassword" category="users" type="boolean" default="1" />
  </settings>
    
  <actions>
	<action id="login" controller="FormLoginController" role="guest">
		<param id="loginstr" type="text" required="true"/>
		<param id="loginpassword" type="text" required="true" max="32" />
		<param id="rememberme" type="boolean" />
	</action>
	
	<action id="send-password" controller="SendPasswordController" role="guest">
		<param id="useremail" type="text" required="true" validator="EmailValidator"/>
	</action>
	
	<action id="activate" controller="UserActivationController" role="guest">
		<param id="userid" type="number" required="true" />
		<param id="key" type="text" required="true" />
	</action>
  </actions>

</module>

=== astroChasqui/websoccer_es/modules/formation/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

    <dependencies>
        <dependency module="office" version="1.0.0" />
        <dependency module="matches" version="1.0.0" />
    </dependencies>
    
    <settings>
      <setting id="formation_max_next_matches" category="game" type="number" default="3" />
      <setting id="formation_max_templates" category="game" type="number" default="10" />
    </settings>
    
    <pages>
        <page
            id="formation"
            template="formation"
            model="FormationModel"
            navitem="true"
            navweight="0"
            role="user"
            parentItem="office">
            
            <script file="jquery-ui-1.10.2.custom.min.js" debugonly="true"/>
            <script file="formationws4.js?v=5" debugonly="true"/>
            <script file="formation.min.js?v=5" productiononly="true"/>
            
            <script file="bootstrap-slider.js" />
            <script file="bootstrap-switch.js" />
            
            <css file="slider.css"/>
        	<css file="formation.css"/>
        	<css file="bootstrap-switch.css"/>
        </page>

    </pages> 
    
    <blocks>

        <block
            id="nextmatch_with_formationlink"
            template="nextmatch_with_formationlink"
            model="NextMatchModel"
            includepages="office"
            area="content_top"
            weight="0"
            role="user" />
        
        <block
            id="formation_templates"
            template="formation_templates"
            model="FormationTemplatesModel"
            includepages="none"
            area="custom"
            role="user" />
        
    </blocks>
    
  <actions>
	<action id="save-formation" controller="SaveFormationController" role="user" log="true">
	    <param id="id" type="number" required="true" />
	    
		<param id="offensive" type="number" required="true" min="1" max="100" />
		<param id="setup" type="text" required="true" />
		
		<param id="longpasses" type="boolean" />
		<param id="counterattacks" type="boolean" />
		<param id="freekickplayer" type="number" />
		
		<param id="player1" type="number" required="true" />
		<param id="player2" type="number" required="true" />
		<param id="player3" type="number" required="true" />
		<param id="player4" type="number" required="true" />
		<param id="player5" type="number" required="true" />
		<param id="player6" type="number" required="true" />
		<param id="player7" type="number" required="true" />
		<param id="player8" type="number" required="true" />
		<param id="player9" type="number" required="true" />
		<param id="player10" type="number" required="true" />
		<param id="player11" type="number" required="true" />
		<param id="bench1" type="number" />
		<param id="bench2" type="number" />
		<param id="bench3" type="number" />
		<param id="bench4" type="number" />
		<param id="bench5" type="number" />
		<param id="player1_pos" type="text" required="true" />
		<param id="player2_pos" type="text" required="true" />
		<param id="player3_pos" type="text" required="true" />
		<param id="player4_pos" type="text" required="true" />
		<param id="player5_pos" type="text" required="true" />
		<param id="player6_pos" type="text" required="true" />
		<param id="player7_pos" type="text" required="true" />
		<param id="player8_pos" type="text" required="true" />
		<param id="player9_pos" type="text" required="true" />
		<param id="player10_pos" type="text" required="true" />
		<param id="player11_pos" type="text" required="true" />
		
		<param id="sub1_out" type="number" />
		<param id="sub1_in" type="number" />
		<param id="sub1_minute" type="number"/>
		<param id="sub1_condition" type="text" />
		<param id="sub1_position" type="text" />
		
		<param id="sub2_out" type="number" />
		<param id="sub2_in" type="number" />
		<param id="sub2_minute" type="number" />
		<param id="sub2_condition" type="text" />
		<param id="sub2_position" type="text" />
		
		<param id="sub3_out" type="number" />
		<param id="sub3_in" type="number" />
		<param id="sub3_minute" type="number" />
		<param id="sub3_condition" type="text" />
		<param id="sub3_position" type="text" />
		
		<param id="templatename" type="text" max="24" />
	</action>
	
	<action id="remove-formation-template" controller="RemoveFormationTemplateController" role="user">
	    <param id="templateid" type="number" required="true" />
	</action>
  </actions>
    
</module>

=== astroChasqui/websoccer_es/modules/premiummicropayment/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
  
  	<settings>
      	<setting id="micropayment_enabled" category="premium" type="boolean" default="false" />
      	<setting id="micropayment_project" category="premium" type="text" default="" />
      	<setting id="micropayment_accesskey" category="premium" type="text" default="" />
      	
      	<setting id="micropayment_call2pay_enabled" category="premium" type="boolean" default="false" />
      	<setting id="micropayment_handypay_enabled" category="premium" type="boolean" default="false" />
      	<setting id="micropayment_ebank2pay_enabled" category="premium" type="boolean" default="false" />
      	<setting id="micropayment_creditcard_enabled" category="premium" type="boolean" default="false" />
  	</settings>
  	
	<actions>
	    
	    <action id="micropayment-redirect" controller="MicropaymentRedirectController" role="user">
	        <param id="amount" type="number" required="true" />
	    </action>
	    
	</actions>
	
	<blocks>
      
       <block
            id="micropaymentlink"
            template="micropaymentlink"
            includepages="premium-feature-requested"
            area="content_bottom"
            weight="1"
            role="user" />
        
	</blocks>
  
</module>

=== astroChasqui/websoccer_es/modules/premiumpaypal/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
  
  	<settings>
      	<setting id="paypal_enabled" category="premium" type="boolean" default="false" />
      	<setting id="paypal_receiver_email" category="premium" type="email" default="" />
      	<setting id="paypal_host" category="premium" type="text" default="www.paypal.com" />
      	<setting id="paypal_url" category="premium" type="url" default="ssl://www.paypal.com" />
      	<setting id="paypal_buttonhtml" category="premium" type="textarea" default="" />
  	</settings>
  	
	<actions>
	    <action id="paypal-notify" controller="PaypalPaymentNotificationController" role="guest,user">
	        <param id="receiver_email" type="email" required="true" />
	        <param id="mc_gross" type="text" required="true" />
	        <param id="settle_amount" type="text" required="false" />
	        <param id="custom" type="number" required="true" />
	        <param id="payment_status" type="text" required="true" />
	        
	    </action>
	    
	</actions>
	
	<blocks>
      
       <block
            id="paypalpaymentlink"
            template="paypalpaymentlink"
            includepages="premium-feature-requested"
            area="content_bottom"
            weight="1"
            role="user"
            model="PaypalLinkModel" />
        
	</blocks>
  
</module>

=== astroChasqui/websoccer_es/modules/tables/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">

    <dependencies>
        <dependency module="leagues" version="1.0.0"/>
    </dependencies>
    
    <admin>
        <adminpage
            id="tablemarker"
            entity="tablemarker"
            navcategory="league"
            permissionrole="r_daten" >

            <entity dbtable="tabelle_markierung AS MarkerTab" >

                <overview delete="true" edit="true" >

                    <column
                        id="entity_tablemarker_bezeichnung"
                        field="MarkerTab.bezeichnung"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_tablemarker_liga_id"
                        field="LeagueTab.name"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_tablemarker_platz_von"
                        field="MarkerTab.platz_von"
                        type="number"
                        sort="true" />
                  
                    <column
                        id="entity_tablemarker_platz_bis"
                        field="MarkerTab.platz_bis"
                        type="number"
                        sort="true" />
                    
                    <column
                        id="entity_tablemarker_target_league_id"
                        field="TargetLeagueTab.name"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    
                	<join type="LEFT" jointable="liga AS LeagueTab" joincondition="MarkerTab.liga_id = LeagueTab.id" />
                	<join type="LEFT" jointable="liga AS TargetLeagueTab" joincondition="MarkerTab.target_league_id = TargetLeagueTab.id" />
                </overview>

                <editform>
                    <field id="bezeichnung" type="text" required="true" />
                    <field id="liga_id" type="foreign_key" entity="league" jointable="liga" cascade="delete" labelcolumns="land, name" required="true" />
					<field id="platz_von" type="number" required="true" />
					<field id="platz_bis" type="number" required="true" />
					<field id="farbe" type="color" required="true" />
					<field id="target_league_id" type="foreign_key" entity="league" jointable="liga" labelcolumns="land, name" required="false" />
                </editform>
            </entity>
        </adminpage>
    </admin>
    
    <pages>
        <page
            id="tablehistory"
            template="tablehistory"
            model="TableHistoryModel"
            role="user,guest"
            parentItem="league">
            <script file="flot/jquery.flot.min.js" />
            <script file="charts.js" />
        </page>

    </pages> 
    
</module>

=== astroChasqui/websoccer_es/modules/leagues/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
    
    <admin>
        <adminpage
            id="league"
            entity="league"
            navcategory="league"
            permissionrole="r_daten" >

            <entity dbtable="liga" >

                <overview
                    delete="true"
                    edit="true" >

                    <column
                        id="entity_league_name"
                        field="name"
                        type="text"
                        sort="true"
                        filter="true" />

                    <column
                        id="entity_league_kurz"
                        field="kurz"
                        type="text"
                        sort="true"
                        filter="true" />
                    
                    <column
                        id="entity_league_land"
                        field="land"
                        type="text"
                        sort="true"
                        filter="true" />
                </overview>

                <editform>

                    <field
                        id="name"
                        type="text"
                        required="true"  />

                    <field
                        id="kurz"
                        type="text"
                        required="true"  />
                    
                    <field
                        id="land"
                        type="text"
                        required="true"  />
                    
                    <field
                        id="p_steh"
                        type="percent"
                        required="true"  />
                    <field
                        id="p_sitz"
                        type="percent"
                        required="true"  />
                    <field
                        id="p_haupt_steh"
                        type="percent"
                        required="true"  />
                    <field
                        id="p_haupt_sitz"
                        type="percent"
                        required="true"  />
                    <field
                        id="p_vip"
                        type="percent"
                        required="true"  />
                    <field
                        id="preis_steh"
                        type="number"
                        required="true"  />
                    <field
                        id="preis_sitz"
                        type="number"
                        required="true"  />
                    <field
                        id="preis_vip"
                        type="number"
                        required="true"  />
                </editform>
            </entity>
        </adminpage>
    </admin>
    
    <pages>
        <page
            id="leagues"
            template="league-details"
            navitem="true"
            navweight="3"
            model="LeagueDetailsModel"
            role="user,guest">
	        <page
	            id="results"
	            template="results-overview"
	            navitem="true"
	            model="LeaguesListModel"
	            navweight="0"
	            role="user,guest"/>
	        
   
        </page>
        
        <!-- Deprecated page. Only have it for backwards compatibility. -->
        <page
	            id="league"
	            template="league-details"
	            model="LeagueDetailsModel"
	            role="user,guest"/>	     

    </pages> 
    
    <blocks>

        <block
            id="leaguetable"
            template="league_table"
            model="LeagueTableModel"
            includepages="leagues,league"
            area="content_bottom"
            weight="2"
            role="user,guest" />
        
    </blocks>
    
</module>

=== astroChasqui/websoccer_es/modules/premiumsofortcom/module.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE module SYSTEM "../module.dtd">
<module version="1.0.0">
  
  	<settings>
      	<setting id="sofortcom_enabled" category="premium" type="boolean" default="false" />
      	<setting id="sofortcom_configkey" category="premium" type="text" default="" />
  	</settings>
  	
	<actions>
	    <action id="sofortcom-notify" controller="SofortComPaymentNotificationController" role="guest,user">
	        <param id="u" type="number" required="true" />
	    </action>
	    
	    <action id="sofortcom-redirect" controller="SofortComRedirectController" role="user">
	        <param id="amount" type="number" required="true" min="1" />
	    </action>
	    
	</actions>
	
	<blocks>
      
       <block
            id="sofortcompaymentlink"
            template="sofortcompaymentlink"
            includepages="premium-feature-requested"
            area="content_bottom"
            weight="1"
            role="user" />
        
	</blocks>
  
</module>
